/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dash.sdk;

public class ChainType {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ChainType(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ChainType obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        exampleJNI.delete_ChainType(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTag(ChainType_Tag value) {
    exampleJNI.ChainType_tag_set(swigCPtr, this, value.swigValue());
  }

  public ChainType_Tag getTag() {
    return ChainType_Tag.swigToEnum(exampleJNI.ChainType_tag_get(swigCPtr, this));
  }

  public void setDev_net(SWIGTYPE_p_DevnetType value) {
    exampleJNI.ChainType_dev_net_set(swigCPtr, this, SWIGTYPE_p_DevnetType.getCPtr(value));
  }

  public SWIGTYPE_p_DevnetType getDev_net() {
    long cPtr = exampleJNI.ChainType_dev_net_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_DevnetType(cPtr, false);
  }

}
