/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dash.sdk;

public final class ChainType_Tag {
  public final static ChainType_Tag ChainType_MainNet = new ChainType_Tag("ChainType_MainNet");
  public final static ChainType_Tag ChainType_TestNet = new ChainType_Tag("ChainType_TestNet");
  public final static ChainType_Tag ChainType_DevNet = new ChainType_Tag("ChainType_DevNet");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ChainType_Tag swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ChainType_Tag.class + " with value " + swigValue);
  }

  private ChainType_Tag(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ChainType_Tag(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ChainType_Tag(String swigName, ChainType_Tag swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ChainType_Tag[] swigValues = { ChainType_MainNet, ChainType_TestNet, ChainType_DevNet };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

