/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dash.sdk;

public final class ChainType_FFI {
  public final static ChainType_FFI ChainType_FFI_MainNet = new ChainType_FFI("ChainType_FFI_MainNet");
  public final static ChainType_FFI ChainType_FFI_TestNet = new ChainType_FFI("ChainType_FFI_TestNet");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ChainType_FFI swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ChainType_FFI.class + " with value " + swigValue);
  }

  private ChainType_FFI(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ChainType_FFI(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ChainType_FFI(String swigName, ChainType_FFI swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ChainType_FFI[] swigValues = { ChainType_FFI_MainNet, ChainType_FFI_TestNet };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

