/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dash.sdk;

public class DataContractNotPresentError_FFI {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected DataContractNotPresentError_FFI(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DataContractNotPresentError_FFI obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        exampleJNI.delete_DataContractNotPresentError_FFI(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setData_contract_id(Identifier value) {
    exampleJNI.DataContractNotPresentError_FFI_data_contract_id_set(swigCPtr, this, Identifier.getCPtr(value), value);
  }

  public Identifier getData_contract_id() {
    long cPtr = exampleJNI.DataContractNotPresentError_FFI_data_contract_id_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Identifier(cPtr, false);
  }

  public DataContractNotPresentError_FFI() {
    this(exampleJNI.new_DataContractNotPresentError_FFI(), true);
  }

}
