/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dash.sdk;

public final class DevnetType_FFI {
  public final static DevnetType_FFI DevnetType_FFI_JackDaniels = new DevnetType_FFI("DevnetType_FFI_JackDaniels", exampleJNI.DevnetType_FFI_JackDaniels_get());
  public final static DevnetType_FFI DevnetType_FFI_Devnet333 = new DevnetType_FFI("DevnetType_FFI_Devnet333", exampleJNI.DevnetType_FFI_Devnet333_get());
  public final static DevnetType_FFI DevnetType_FFI_Chacha = new DevnetType_FFI("DevnetType_FFI_Chacha", exampleJNI.DevnetType_FFI_Chacha_get());
  public final static DevnetType_FFI DevnetType_FFI_Mojito = new DevnetType_FFI("DevnetType_FFI_Mojito", exampleJNI.DevnetType_FFI_Mojito_get());
  public final static DevnetType_FFI DevnetType_FFI_WhiteRussian = new DevnetType_FFI("DevnetType_FFI_WhiteRussian", exampleJNI.DevnetType_FFI_WhiteRussian_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static DevnetType_FFI swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + DevnetType_FFI.class + " with value " + swigValue);
  }

  private DevnetType_FFI(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private DevnetType_FFI(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private DevnetType_FFI(String swigName, DevnetType_FFI swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static DevnetType_FFI[] swigValues = { DevnetType_FFI_JackDaniels, DevnetType_FFI_Devnet333, DevnetType_FFI_Chacha, DevnetType_FFI_Mojito, DevnetType_FFI_WhiteRussian };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

