/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dash.sdk;

public final class DevnetType {
  public final static DevnetType DevnetType_JackDaniels = new DevnetType("DevnetType_JackDaniels", exampleJNI.DevnetType_JackDaniels_get());
  public final static DevnetType DevnetType_Devnet333 = new DevnetType("DevnetType_Devnet333", exampleJNI.DevnetType_Devnet333_get());
  public final static DevnetType DevnetType_Chacha = new DevnetType("DevnetType_Chacha", exampleJNI.DevnetType_Chacha_get());
  public final static DevnetType DevnetType_Mojito = new DevnetType("DevnetType_Mojito", exampleJNI.DevnetType_Mojito_get());
  public final static DevnetType DevnetType_WhiteRussian = new DevnetType("DevnetType_WhiteRussian", exampleJNI.DevnetType_WhiteRussian_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static DevnetType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + DevnetType.class + " with value " + swigValue);
  }

  private DevnetType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private DevnetType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private DevnetType(String swigName, DevnetType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static DevnetType[] swigValues = { DevnetType_JackDaniels, DevnetType_Devnet333, DevnetType_Chacha, DevnetType_Mojito, DevnetType_WhiteRussian };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

