/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dash.sdk;

public class exampleJNI {
  public final static native void HashID__0_set(long jarg1, HashID jarg1_, byte[] jarg2);
  public final static native byte[] HashID__0_get(long jarg1, HashID jarg1_);
  public final static native long new_HashID();
  public final static native void delete_HashID(long jarg1);
  public final static native void std_collections_Map_keys_crate_chain_common_chain_type_ChainType_values_crate_nested_HashID_FFI_count_set(long jarg1, std_collections_Map_keys_crate_chain_common_chain_type_ChainType_values_crate_nested_HashID_FFI jarg1_, long jarg2);
  public final static native long std_collections_Map_keys_crate_chain_common_chain_type_ChainType_values_crate_nested_HashID_FFI_count_get(long jarg1, std_collections_Map_keys_crate_chain_common_chain_type_ChainType_values_crate_nested_HashID_FFI jarg1_);
  public final static native void std_collections_Map_keys_crate_chain_common_chain_type_ChainType_values_crate_nested_HashID_FFI_keys_set(long jarg1, std_collections_Map_keys_crate_chain_common_chain_type_ChainType_values_crate_nested_HashID_FFI jarg1_, long jarg2);
  public final static native long std_collections_Map_keys_crate_chain_common_chain_type_ChainType_values_crate_nested_HashID_FFI_keys_get(long jarg1, std_collections_Map_keys_crate_chain_common_chain_type_ChainType_values_crate_nested_HashID_FFI jarg1_);
  public final static native void std_collections_Map_keys_crate_chain_common_chain_type_ChainType_values_crate_nested_HashID_FFI_values_set(long jarg1, std_collections_Map_keys_crate_chain_common_chain_type_ChainType_values_crate_nested_HashID_FFI jarg1_, long jarg2);
  public final static native long std_collections_Map_keys_crate_chain_common_chain_type_ChainType_values_crate_nested_HashID_FFI_values_get(long jarg1, std_collections_Map_keys_crate_chain_common_chain_type_ChainType_values_crate_nested_HashID_FFI jarg1_);
  public final static native long new_std_collections_Map_keys_crate_chain_common_chain_type_ChainType_values_crate_nested_HashID_FFI();
  public final static native void delete_std_collections_Map_keys_crate_chain_common_chain_type_ChainType_values_crate_nested_HashID_FFI(long jarg1);
  public final static native void Vec_u8_FFI_count_set(long jarg1, Vec_u8_FFI jarg1_, long jarg2);
  public final static native long Vec_u8_FFI_count_get(long jarg1, Vec_u8_FFI jarg1_);
  public final static native void Vec_u8_FFI_values_set(long jarg1, Vec_u8_FFI jarg1_, long jarg2);
  public final static native long Vec_u8_FFI_values_get(long jarg1, Vec_u8_FFI jarg1_);
  public final static native long new_Vec_u8_FFI();
  public final static native void delete_Vec_u8_FFI(long jarg1);
  public final static native void IdentifierBytes32__0_set(long jarg1, IdentifierBytes32 jarg1_, byte[] jarg2);
  public final static native byte[] IdentifierBytes32__0_get(long jarg1, IdentifierBytes32 jarg1_);
  public final static native long new_IdentifierBytes32();
  public final static native void delete_IdentifierBytes32(long jarg1);
  public final static native void Identifier__0_set(long jarg1, Identifier jarg1_, long jarg2, IdentifierBytes32 jarg2_);
  public final static native long Identifier__0_get(long jarg1, Identifier jarg1_);
  public final static native long new_Identifier();
  public final static native void delete_Identifier(long jarg1);
  public final static native void KeyID__0_set(long jarg1, KeyID jarg1_, long jarg2);
  public final static native long KeyID__0_get(long jarg1, KeyID jarg1_);
  public final static native long new_KeyID();
  public final static native void delete_KeyID(long jarg1);
  public final static native void IdentityPublicKey_tag_set(long jarg1, IdentityPublicKey jarg1_, int jarg2);
  public final static native int IdentityPublicKey_tag_get(long jarg1, IdentityPublicKey jarg1_);
  public final static native void IdentityPublicKey_v0_set(long jarg1, IdentityPublicKey jarg1_, long jarg2);
  public final static native long IdentityPublicKey_v0_get(long jarg1, IdentityPublicKey jarg1_);
  public final static native long new_IdentityPublicKey();
  public final static native void delete_IdentityPublicKey(long jarg1);
  public final static native void std_collections_Map_keys_crate_nested_KeyID_values_crate_nested_IdentityPublicKey_FFI_count_set(long jarg1, std_collections_Map_keys_crate_nested_KeyID_values_crate_nested_IdentityPublicKey_FFI jarg1_, long jarg2);
  public final static native long std_collections_Map_keys_crate_nested_KeyID_values_crate_nested_IdentityPublicKey_FFI_count_get(long jarg1, std_collections_Map_keys_crate_nested_KeyID_values_crate_nested_IdentityPublicKey_FFI jarg1_);
  public final static native void std_collections_Map_keys_crate_nested_KeyID_values_crate_nested_IdentityPublicKey_FFI_keys_set(long jarg1, std_collections_Map_keys_crate_nested_KeyID_values_crate_nested_IdentityPublicKey_FFI jarg1_, long jarg2);
  public final static native long std_collections_Map_keys_crate_nested_KeyID_values_crate_nested_IdentityPublicKey_FFI_keys_get(long jarg1, std_collections_Map_keys_crate_nested_KeyID_values_crate_nested_IdentityPublicKey_FFI jarg1_);
  public final static native void std_collections_Map_keys_crate_nested_KeyID_values_crate_nested_IdentityPublicKey_FFI_values_set(long jarg1, std_collections_Map_keys_crate_nested_KeyID_values_crate_nested_IdentityPublicKey_FFI jarg1_, long jarg2);
  public final static native long std_collections_Map_keys_crate_nested_KeyID_values_crate_nested_IdentityPublicKey_FFI_values_get(long jarg1, std_collections_Map_keys_crate_nested_KeyID_values_crate_nested_IdentityPublicKey_FFI jarg1_);
  public final static native long new_std_collections_Map_keys_crate_nested_KeyID_values_crate_nested_IdentityPublicKey_FFI();
  public final static native void delete_std_collections_Map_keys_crate_nested_KeyID_values_crate_nested_IdentityPublicKey_FFI(long jarg1);
  public final static native void Revision__0_set(long jarg1, Revision jarg1_, java.math.BigInteger jarg2);
  public final static native java.math.BigInteger Revision__0_get(long jarg1, Revision jarg1_);
  public final static native long new_Revision();
  public final static native void delete_Revision(long jarg1);
  public final static native void IdentityV0_id_set(long jarg1, IdentityV0 jarg1_, long jarg2, Identifier jarg2_);
  public final static native long IdentityV0_id_get(long jarg1, IdentityV0 jarg1_);
  public final static native void IdentityV0_public_keys_set(long jarg1, IdentityV0 jarg1_, long jarg2, std_collections_Map_keys_crate_nested_KeyID_values_crate_nested_IdentityPublicKey_FFI jarg2_);
  public final static native long IdentityV0_public_keys_get(long jarg1, IdentityV0 jarg1_);
  public final static native void IdentityV0_balance_set(long jarg1, IdentityV0 jarg1_, java.math.BigInteger jarg2);
  public final static native java.math.BigInteger IdentityV0_balance_get(long jarg1, IdentityV0 jarg1_);
  public final static native void IdentityV0_revision_set(long jarg1, IdentityV0 jarg1_, long jarg2, Revision jarg2_);
  public final static native long IdentityV0_revision_get(long jarg1, IdentityV0 jarg1_);
  public final static native long new_IdentityV0();
  public final static native void delete_IdentityV0(long jarg1);
  public final static native void Identity_tag_set(long jarg1, Identity jarg1_, int jarg2);
  public final static native int Identity_tag_get(long jarg1, Identity jarg1_);
  public final static native void Identity_v0_set(long jarg1, Identity jarg1_, long jarg2, IdentityV0 jarg2_);
  public final static native long Identity_v0_get(long jarg1, Identity jarg1_);
  public final static native long new_Identity();
  public final static native void delete_Identity(long jarg1);
  public final static native void std_collections_Map_keys_u32_values_crate_nested_HashID_FFI_count_set(long jarg1, std_collections_Map_keys_u32_values_crate_nested_HashID_FFI jarg1_, long jarg2);
  public final static native long std_collections_Map_keys_u32_values_crate_nested_HashID_FFI_count_get(long jarg1, std_collections_Map_keys_u32_values_crate_nested_HashID_FFI jarg1_);
  public final static native void std_collections_Map_keys_u32_values_crate_nested_HashID_FFI_keys_set(long jarg1, std_collections_Map_keys_u32_values_crate_nested_HashID_FFI jarg1_, long jarg2);
  public final static native long std_collections_Map_keys_u32_values_crate_nested_HashID_FFI_keys_get(long jarg1, std_collections_Map_keys_u32_values_crate_nested_HashID_FFI jarg1_);
  public final static native void std_collections_Map_keys_u32_values_crate_nested_HashID_FFI_values_set(long jarg1, std_collections_Map_keys_u32_values_crate_nested_HashID_FFI jarg1_, long jarg2);
  public final static native long std_collections_Map_keys_u32_values_crate_nested_HashID_FFI_values_get(long jarg1, std_collections_Map_keys_u32_values_crate_nested_HashID_FFI jarg1_);
  public final static native long new_std_collections_Map_keys_u32_values_crate_nested_HashID_FFI();
  public final static native void delete_std_collections_Map_keys_u32_values_crate_nested_HashID_FFI(long jarg1);
  public final static native String get_chain_hashes_by_map(long jarg1, std_collections_Map_keys_crate_chain_common_chain_type_ChainType_values_crate_nested_HashID_FFI jarg1_);
  public final static native String get_chain_type_string(long jarg1);
  public final static native String address_with_script_pubkey(long jarg1, Vec_u8_FFI jarg1_);
  public final static native long get_an_identity();
  public final static native long find_hash_by_u32(long jarg1, long jarg2, std_collections_Map_keys_u32_values_crate_nested_HashID_FFI jarg2_);
  public final static native long get_identity(long jarg1, Identifier jarg1_);
}
