/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dash.sdk;

public class Hash160 {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Hash160(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Hash160 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        exampleJNI.delete_Hash160(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void set_0(SWIGTYPE_p_a_20__unsigned_char value) {
    exampleJNI.Hash160__0_set(swigCPtr, this, SWIGTYPE_p_a_20__unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_a_20__unsigned_char get_0() {
    long cPtr = exampleJNI.Hash160__0_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_20__unsigned_char(cPtr, false);
  }

}
