/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dash.sdk;

public class IdentityFactory_TraitObject {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected IdentityFactory_TraitObject(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IdentityFactory_TraitObject obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        exampleJNI.delete_IdentityFactory_TraitObject(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setObject(SWIGTYPE_p_void value) {
    exampleJNI.IdentityFactory_TraitObject_object_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getObject() {
    long cPtr = exampleJNI.IdentityFactory_TraitObject_object_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setVtable(IdentityFactory_VTable value) {
    exampleJNI.IdentityFactory_TraitObject_vtable_set(swigCPtr, this, IdentityFactory_VTable.getCPtr(value), value);
  }

  public IdentityFactory_VTable getVtable() {
    long cPtr = exampleJNI.IdentityFactory_TraitObject_vtable_get(swigCPtr, this);
    return (cPtr == 0) ? null : new IdentityFactory_VTable(cPtr, false);
  }

  public IdentityFactory_TraitObject() {
    this(exampleJNI.new_IdentityFactory_TraitObject(), true);
  }

}
