/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dash.sdk;

public final class IdentityPublicKeyTag {
  public final static IdentityPublicKeyTag IdentityPublicKey_FFI_V0 = new IdentityPublicKeyTag("IdentityPublicKey_FFI_V0");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static IdentityPublicKeyTag swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + IdentityPublicKeyTag.class + " with value " + swigValue);
  }

  private IdentityPublicKeyTag(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private IdentityPublicKeyTag(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private IdentityPublicKeyTag(String swigName, IdentityPublicKeyTag swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static IdentityPublicKeyTag[] swigValues = { IdentityPublicKey_FFI_V0 };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

