/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dash.sdk;

public class IdentityFactory_VTable {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected IdentityFactory_VTable(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IdentityFactory_VTable obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        exampleJNI.delete_IdentityFactory_VTable(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setGet_identity(SWIGTYPE_p_f_p_q_const__void_p_Identifier_FFI__p_Identity_FFI value) {
    exampleJNI.IdentityFactory_VTable_get_identity_set(swigCPtr, this, SWIGTYPE_p_f_p_q_const__void_p_Identifier_FFI__p_Identity_FFI.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_q_const__void_p_Identifier_FFI__p_Identity_FFI getGet_identity() {
    long cPtr = exampleJNI.IdentityFactory_VTable_get_identity_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_q_const__void_p_Identifier_FFI__p_Identity_FFI(cPtr, false);
  }

  public IdentityFactory_VTable() {
    this(exampleJNI.new_IdentityFactory_VTable(), true);
  }

}
