/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dash.sdk;

public class IHaveChainSettings {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected IHaveChainSettings(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IHaveChainSettings obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        exampleJNI.delete_IHaveChainSettings(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public IHaveChainSettings(IHaveChainSettings_TraitObject traitObject) {
    this(exampleJNI.new_IHaveChainSettings(IHaveChainSettings_TraitObject.getCPtr(traitObject), traitObject), true);
  }

  public String name() {
    return exampleJNI.IHaveChainSettings_name(swigCPtr, this);
  }

  public HashID genesisHash() {
    long cPtr = exampleJNI.IHaveChainSettings_genesisHash(swigCPtr, this);
    return (cPtr == 0) ? null : new HashID(cPtr, false);
  }

  public long genesisHeight() {
    return exampleJNI.IHaveChainSettings_genesisHeight(swigCPtr, this);
  }

  public boolean hasGenesisHash(HashID hash) {
    return exampleJNI.IHaveChainSettings_hasGenesisHash(swigCPtr, this, HashID.getCPtr(hash), hash);
  }

  public HashID getHashByHash(HashID hash) {
    long cPtr = exampleJNI.IHaveChainSettings_getHashByHash(swigCPtr, this, HashID.getCPtr(hash), hash);
    return (cPtr == 0) ? null : new HashID(cPtr, false);
  }

  public boolean shouldProcessLlmqOfType(int llmq_type) {
    return exampleJNI.IHaveChainSettings_shouldProcessLlmqOfType(swigCPtr, this, llmq_type);
  }

}
