/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dash.sdk;

public class IHaveChainSettings_VTable {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected IHaveChainSettings_VTable(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IHaveChainSettings_VTable obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        exampleJNI.delete_IHaveChainSettings_VTable(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setName(SWIGTYPE_p_f_p_q_const__void__p_char value) {
    exampleJNI.IHaveChainSettings_VTable_name_set(swigCPtr, this, SWIGTYPE_p_f_p_q_const__void__p_char.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_q_const__void__p_char getName() {
    long cPtr = exampleJNI.IHaveChainSettings_VTable_name_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_q_const__void__p_char(cPtr, false);
  }

  public void setGenesis_hash(SWIGTYPE_p_f_p_q_const__void__p_HashID_FFI value) {
    exampleJNI.IHaveChainSettings_VTable_genesis_hash_set(swigCPtr, this, SWIGTYPE_p_f_p_q_const__void__p_HashID_FFI.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_q_const__void__p_HashID_FFI getGenesis_hash() {
    long cPtr = exampleJNI.IHaveChainSettings_VTable_genesis_hash_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_q_const__void__p_HashID_FFI(cPtr, false);
  }

  public void setGenesis_height(SWIGTYPE_p_f_p_q_const__void__unsigned_int value) {
    exampleJNI.IHaveChainSettings_VTable_genesis_height_set(swigCPtr, this, SWIGTYPE_p_f_p_q_const__void__unsigned_int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_q_const__void__unsigned_int getGenesis_height() {
    long cPtr = exampleJNI.IHaveChainSettings_VTable_genesis_height_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_q_const__void__unsigned_int(cPtr, false);
  }

  public void setHas_genesis_hash(SWIGTYPE_p_f_p_q_const__void_p_HashID_FFI__bool value) {
    exampleJNI.IHaveChainSettings_VTable_has_genesis_hash_set(swigCPtr, this, SWIGTYPE_p_f_p_q_const__void_p_HashID_FFI__bool.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_q_const__void_p_HashID_FFI__bool getHas_genesis_hash() {
    long cPtr = exampleJNI.IHaveChainSettings_VTable_has_genesis_hash_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_q_const__void_p_HashID_FFI__bool(cPtr, false);
  }

  public void setGet_hash_by_hash(SWIGTYPE_p_f_p_q_const__void_p_HashID_FFI__p_HashID_FFI value) {
    exampleJNI.IHaveChainSettings_VTable_get_hash_by_hash_set(swigCPtr, this, SWIGTYPE_p_f_p_q_const__void_p_HashID_FFI__p_HashID_FFI.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_q_const__void_p_HashID_FFI__p_HashID_FFI getGet_hash_by_hash() {
    long cPtr = exampleJNI.IHaveChainSettings_VTable_get_hash_by_hash_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_q_const__void_p_HashID_FFI__p_HashID_FFI(cPtr, false);
  }

  public void setShould_process_llmq_of_type(SWIGTYPE_p_f_p_q_const__void_unsigned_short__bool value) {
    exampleJNI.IHaveChainSettings_VTable_should_process_llmq_of_type_set(swigCPtr, this, SWIGTYPE_p_f_p_q_const__void_unsigned_short__bool.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_q_const__void_unsigned_short__bool getShould_process_llmq_of_type() {
    long cPtr = exampleJNI.IHaveChainSettings_VTable_should_process_llmq_of_type_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_q_const__void_unsigned_short__bool(cPtr, false);
  }

  public IHaveChainSettings_VTable() {
    this(exampleJNI.new_IHaveChainSettings_VTable(), true);
  }

}
