/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dash.sdk;

public class KeyID {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected KeyID(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(KeyID obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        exampleJNI.delete_KeyID(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void set_0(long value) {
    exampleJNI.KeyID__0_set(swigCPtr, this, value);
  }

  public long get_0() {
    return exampleJNI.KeyID__0_get(swigCPtr, this);
  }

  public KeyID() {
    this(exampleJNI.new_KeyID(), true);
  }

}
