/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dash.sdk;

public class MapOfHashes {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MapOfHashes(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MapOfHashes obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        exampleJNI.delete_MapOfHashes(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void set_0(std_collections_Map_keys_crate_nested_HashID_values_crate_nested_HashID value) {
    exampleJNI.MapOfHashes__0_set(swigCPtr, this, std_collections_Map_keys_crate_nested_HashID_values_crate_nested_HashID.getCPtr(value), value);
  }

  public std_collections_Map_keys_crate_nested_HashID_values_crate_nested_HashID get_0() {
    long cPtr = exampleJNI.MapOfHashes__0_get(swigCPtr, this);
    return (cPtr == 0) ? null : new std_collections_Map_keys_crate_nested_HashID_values_crate_nested_HashID(cPtr, false);
  }

}
