/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dash.sdk;

public class MapOfVecHashes_FFI {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MapOfVecHashes_FFI(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MapOfVecHashes_FFI obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        exampleJNI.delete_MapOfVecHashes_FFI(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void set_0(std_collections_Map_keys_crate_nested_HashID_values_Vec_crate_nested_HashID_FFI value) {
    exampleJNI.MapOfVecHashes_FFI__0_set(swigCPtr, this, std_collections_Map_keys_crate_nested_HashID_values_Vec_crate_nested_HashID_FFI.getCPtr(value), value);
  }

  public std_collections_Map_keys_crate_nested_HashID_values_Vec_crate_nested_HashID_FFI get_0() {
    long cPtr = exampleJNI.MapOfVecHashes_FFI__0_get(swigCPtr, this);
    return (cPtr == 0) ? null : new std_collections_Map_keys_crate_nested_HashID_values_Vec_crate_nested_HashID_FFI(cPtr, false);
  }

  public MapOfVecHashes_FFI() {
    this(exampleJNI.new_MapOfVecHashes_FFI(), true);
  }

}
