/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dash.sdk;

public class MyIdentityFactory_FFI {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MyIdentityFactory_FFI(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MyIdentityFactory_FFI obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        exampleJNI.delete_MyIdentityFactory_FFI(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setFirst(long value) {
    exampleJNI.MyIdentityFactory_FFI_first_set(swigCPtr, this, value);
  }

  public long getFirst() {
    return exampleJNI.MyIdentityFactory_FFI_first_get(swigCPtr, this);
  }

  public MyIdentityFactory_FFI() {
    this(exampleJNI.new_MyIdentityFactory_FFI(), true);
  }

}
