/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dash.sdk;

public final class ProtocolError_FFI_Tag {
  public final static ProtocolError_FFI_Tag ProtocolError_FFI_IdentifierError = new ProtocolError_FFI_Tag("ProtocolError_FFI_IdentifierError");
  public final static ProtocolError_FFI_Tag ProtocolError_FFI_StringDecodeError = new ProtocolError_FFI_Tag("ProtocolError_FFI_StringDecodeError");
  public final static ProtocolError_FFI_Tag ProtocolError_FFI_StringDecodeError2 = new ProtocolError_FFI_Tag("ProtocolError_FFI_StringDecodeError2");
  public final static ProtocolError_FFI_Tag ProtocolError_FFI_EmptyPublicKeyDataError = new ProtocolError_FFI_Tag("ProtocolError_FFI_EmptyPublicKeyDataError");
  public final static ProtocolError_FFI_Tag ProtocolError_FFI_MaxEncodedBytesReachedError = new ProtocolError_FFI_Tag("ProtocolError_FFI_MaxEncodedBytesReachedError");
  public final static ProtocolError_FFI_Tag ProtocolError_FFI_EncodingError = new ProtocolError_FFI_Tag("ProtocolError_FFI_EncodingError");
  public final static ProtocolError_FFI_Tag ProtocolError_FFI_EncodingError2 = new ProtocolError_FFI_Tag("ProtocolError_FFI_EncodingError2");
  public final static ProtocolError_FFI_Tag ProtocolError_FFI_UnknownVersionMismatch = new ProtocolError_FFI_Tag("ProtocolError_FFI_UnknownVersionMismatch");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ProtocolError_FFI_Tag swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ProtocolError_FFI_Tag.class + " with value " + swigValue);
  }

  private ProtocolError_FFI_Tag(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ProtocolError_FFI_Tag(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ProtocolError_FFI_Tag(String swigName, ProtocolError_FFI_Tag swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ProtocolError_FFI_Tag[] swigValues = { ProtocolError_FFI_IdentifierError, ProtocolError_FFI_StringDecodeError, ProtocolError_FFI_StringDecodeError2, ProtocolError_FFI_EmptyPublicKeyDataError, ProtocolError_FFI_MaxEncodedBytesReachedError, ProtocolError_FFI_EncodingError, ProtocolError_FFI_EncodingError2, ProtocolError_FFI_UnknownVersionMismatch };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

