/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dash.sdk;

public class ProtocolError_FFI {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ProtocolError_FFI(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ProtocolError_FFI obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        exampleJNI.delete_ProtocolError_FFI(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTag(ProtocolError_FFI_Tag value) {
    exampleJNI.ProtocolError_FFI_tag_set(swigCPtr, this, value.swigValue());
  }

  public ProtocolError_FFI_Tag getTag() {
    return ProtocolError_FFI_Tag.swigToEnum(exampleJNI.ProtocolError_FFI_tag_get(swigCPtr, this));
  }

  public void setIdentifier_error(String value) {
    exampleJNI.ProtocolError_FFI_identifier_error_set(swigCPtr, this, value);
  }

  public String getIdentifier_error() {
    return exampleJNI.ProtocolError_FFI_identifier_error_get(swigCPtr, this);
  }

  public void setString_decode_error(String value) {
    exampleJNI.ProtocolError_FFI_string_decode_error_set(swigCPtr, this, value);
  }

  public String getString_decode_error() {
    return exampleJNI.ProtocolError_FFI_string_decode_error_get(swigCPtr, this);
  }

  public void setString_decode_error2(ProtocolError_FFI_StringDecodeError2_Body value) {
    exampleJNI.ProtocolError_FFI_string_decode_error2_set(swigCPtr, this, ProtocolError_FFI_StringDecodeError2_Body.getCPtr(value), value);
  }

  public ProtocolError_FFI_StringDecodeError2_Body getString_decode_error2() {
    long cPtr = exampleJNI.ProtocolError_FFI_string_decode_error2_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ProtocolError_FFI_StringDecodeError2_Body(cPtr, false);
  }

  public void setMax_encoded_bytes_reached_error(ProtocolError_FFI_MaxEncodedBytesReachedError_Body value) {
    exampleJNI.ProtocolError_FFI_max_encoded_bytes_reached_error_set(swigCPtr, this, ProtocolError_FFI_MaxEncodedBytesReachedError_Body.getCPtr(value), value);
  }

  public ProtocolError_FFI_MaxEncodedBytesReachedError_Body getMax_encoded_bytes_reached_error() {
    long cPtr = exampleJNI.ProtocolError_FFI_max_encoded_bytes_reached_error_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ProtocolError_FFI_MaxEncodedBytesReachedError_Body(cPtr, false);
  }

  public void setEncoding_error(String value) {
    exampleJNI.ProtocolError_FFI_encoding_error_set(swigCPtr, this, value);
  }

  public String getEncoding_error() {
    return exampleJNI.ProtocolError_FFI_encoding_error_get(swigCPtr, this);
  }

  public void setEncoding_error2(String value) {
    exampleJNI.ProtocolError_FFI_encoding_error2_set(swigCPtr, this, value);
  }

  public String getEncoding_error2() {
    return exampleJNI.ProtocolError_FFI_encoding_error2_get(swigCPtr, this);
  }

  public ProtocolError_FFI() {
    this(exampleJNI.new_ProtocolError_FFI(), true);
  }

}
