/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dash.sdk;

public final class Purpose {
  public final static Purpose Purpose_FFI_AUTHENTICATION = new Purpose("Purpose_FFI_AUTHENTICATION", exampleJNI.Purpose_FFI_AUTHENTICATION_get());
  public final static Purpose Purpose_FFI_ENCRYPTION = new Purpose("Purpose_FFI_ENCRYPTION", exampleJNI.Purpose_FFI_ENCRYPTION_get());
  public final static Purpose Purpose_FFI_DECRYPTION = new Purpose("Purpose_FFI_DECRYPTION", exampleJNI.Purpose_FFI_DECRYPTION_get());
  public final static Purpose Purpose_FFI_WITHDRAW = new Purpose("Purpose_FFI_WITHDRAW", exampleJNI.Purpose_FFI_WITHDRAW_get());
  public final static Purpose Purpose_FFI_SYSTEM = new Purpose("Purpose_FFI_SYSTEM", exampleJNI.Purpose_FFI_SYSTEM_get());
  public final static Purpose Purpose_FFI_VOTING = new Purpose("Purpose_FFI_VOTING", exampleJNI.Purpose_FFI_VOTING_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static Purpose swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + Purpose.class + " with value " + swigValue);
  }

  private Purpose(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private Purpose(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private Purpose(String swigName, Purpose swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static Purpose[] swigValues = { Purpose_FFI_AUTHENTICATION, Purpose_FFI_ENCRYPTION, Purpose_FFI_DECRYPTION, Purpose_FFI_WITHDRAW, Purpose_FFI_SYSTEM, Purpose_FFI_VOTING };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

