/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dash.sdk;

public class SWIGTYPE_p_p_std_collections_Map_keys_crate_nested_HashID_values_crate_nested_HashID {
  private transient long swigCPtr;

  protected SWIGTYPE_p_p_std_collections_Map_keys_crate_nested_HashID_values_crate_nested_HashID(long cPtr, @SuppressWarnings("unused") boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_p_std_collections_Map_keys_crate_nested_HashID_values_crate_nested_HashID() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_p_std_collections_Map_keys_crate_nested_HashID_values_crate_nested_HashID obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

