/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dash.sdk;

public final class TestEnum_Tag {
  public final static TestEnum_Tag TestEnum_Variant1 = new TestEnum_Tag("TestEnum_Variant1");
  public final static TestEnum_Tag TestEnum_Variant2 = new TestEnum_Tag("TestEnum_Variant2");
  public final static TestEnum_Tag TestEnum_Variant3 = new TestEnum_Tag("TestEnum_Variant3");
  public final static TestEnum_Tag TestEnum_Variant4 = new TestEnum_Tag("TestEnum_Variant4");
  public final static TestEnum_Tag TestEnum_Variant5 = new TestEnum_Tag("TestEnum_Variant5");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static TestEnum_Tag swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + TestEnum_Tag.class + " with value " + swigValue);
  }

  private TestEnum_Tag(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private TestEnum_Tag(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private TestEnum_Tag(String swigName, TestEnum_Tag swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static TestEnum_Tag[] swigValues = { TestEnum_Variant1, TestEnum_Variant2, TestEnum_Variant3, TestEnum_Variant4, TestEnum_Variant5 };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

