/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dash.sdk;

public class UnnamedPair {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected UnnamedPair(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(UnnamedPair obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        exampleJNI.delete_UnnamedPair(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void set_0(byte[] value) {
    exampleJNI.UnnamedPair__0_set(swigCPtr, this, value);
  }

  public byte[] get_0() {
    return exampleJNI.UnnamedPair__0_get(swigCPtr, this);
  }

  public void set_1(long value) {
    exampleJNI.UnnamedPair__1_set(swigCPtr, this, value);
  }

  public long get_1() {
    return exampleJNI.UnnamedPair__1_get(swigCPtr, this);
  }

}
