/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dash.sdk;

public class Uri {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Uri(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Uri obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        exampleJNI.delete_Uri(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setScheme(String value) {
    exampleJNI.Uri_scheme_set(swigCPtr, this, value);
  }

  public String getScheme() {
    return exampleJNI.Uri_scheme_get(swigCPtr, this);
  }

}
