/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dash.sdk;

public class UsedStruct {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected UsedStruct(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(UsedStruct obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        exampleJNI.delete_UsedStruct(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void set_0(HashID value) {
    exampleJNI.UsedStruct__0_set(swigCPtr, this, HashID.getCPtr(value), value);
  }

  public HashID get_0() {
    long cPtr = exampleJNI.UsedStruct__0_get(swigCPtr, this);
    return (cPtr == 0) ? null : new HashID(cPtr, false);
  }

}
