/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dash.sdk;

public class UsedKeyMatrix_FFI {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected UsedKeyMatrix_FFI(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(UsedKeyMatrix_FFI obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        exampleJNI.delete_UsedKeyMatrix_FFI(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void set_0(Vec_bool_FFI value) {
    exampleJNI.UsedKeyMatrix_FFI__0_set(swigCPtr, this, Vec_bool_FFI.getCPtr(value), value);
  }

  public Vec_bool_FFI get_0() {
    long cPtr = exampleJNI.UsedKeyMatrix_FFI__0_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Vec_bool_FFI(cPtr, false);
  }

  public UsedKeyMatrix_FFI() {
    this(exampleJNI.new_UsedKeyMatrix_FFI(), true);
  }

}
