/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dash.sdk;

public class Vec_crate_nested_HashID {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Vec_crate_nested_HashID(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Vec_crate_nested_HashID obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        exampleJNI.delete_Vec_crate_nested_HashID(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCount(long value) {
    exampleJNI.Vec_crate_nested_HashID_count_set(swigCPtr, this, value);
  }

  public long getCount() {
    return exampleJNI.Vec_crate_nested_HashID_count_get(swigCPtr, this);
  }

  public void setValues(SWIGTYPE_p_p_HashID value) {
    exampleJNI.Vec_crate_nested_HashID_values_set(swigCPtr, this, SWIGTYPE_p_p_HashID.getCPtr(value));
  }

  public SWIGTYPE_p_p_HashID getValues() {
    long cPtr = exampleJNI.Vec_crate_nested_HashID_values_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_HashID(cPtr, false);
  }

}
