[package]
name = "example"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
rs-ffi-interfaces = { path = "../rs-ffi-interfaces" }
rs-ffi-macro-derive = { path = "../rs-ffi-macro-derive" }

[build-dependencies]
cbindgen = "0.24.3"

[lib]
name = "rs_ffi_interfaces"
