/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */


#ifndef SWIGJAVA
#define SWIGJAVA
#endif


/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTEL_COMPILER)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1,
  SWIG_JavaIOException,
  SWIG_JavaRuntimeException,
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError,
  SWIG_JavaIllegalStateException,
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { SWIG_JavaIllegalStateException, "java/lang/IllegalStateException" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  (*jenv)->ExceptionClear(jenv);
  excep = (*jenv)->FindClass(jenv, except_ptr->java_exception);
  if (excep)
    (*jenv)->ThrowNew(jenv, excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


#include "../../../../ferment-example/target/example.h"
#include <stdlib.h>


#include <stdint.h>		// Use the C99 official header


#if defined(SWIG_NOINCLUDE) || defined(SWIG_NOARRAYS)


static int SWIG_JavaArrayInSchar (JNIEnv *jenv, jbyte **jarr, signed char **carr, jbyteArray input);
static void SWIG_JavaArrayArgoutSchar (JNIEnv *jenv, jbyte *jarr, signed char *carr, jbyteArray input);
static jbyteArray SWIG_JavaArrayOutSchar (JNIEnv *jenv, signed char *result, jsize sz);


static int SWIG_JavaArrayInUchar (JNIEnv *jenv, jshort **jarr, unsigned char **carr, jshortArray input);
static void SWIG_JavaArrayArgoutUchar (JNIEnv *jenv, jshort *jarr, unsigned char *carr, jshortArray input);
static jshortArray SWIG_JavaArrayOutUchar (JNIEnv *jenv, unsigned char *result, jsize sz);


static int SWIG_JavaArrayInShort (JNIEnv *jenv, jshort **jarr, short **carr, jshortArray input);
static void SWIG_JavaArrayArgoutShort (JNIEnv *jenv, jshort *jarr, short *carr, jshortArray input);
static jshortArray SWIG_JavaArrayOutShort (JNIEnv *jenv, short *result, jsize sz);


static int SWIG_JavaArrayInUshort (JNIEnv *jenv, jint **jarr, unsigned short **carr, jintArray input);
static void SWIG_JavaArrayArgoutUshort (JNIEnv *jenv, jint *jarr, unsigned short *carr, jintArray input);
static jintArray SWIG_JavaArrayOutUshort (JNIEnv *jenv, unsigned short *result, jsize sz);


static int SWIG_JavaArrayInInt (JNIEnv *jenv, jint **jarr, int **carr, jintArray input);
static void SWIG_JavaArrayArgoutInt (JNIEnv *jenv, jint *jarr, int *carr, jintArray input);
static jintArray SWIG_JavaArrayOutInt (JNIEnv *jenv, int *result, jsize sz);


static int SWIG_JavaArrayInUint (JNIEnv *jenv, jlong **jarr, unsigned int **carr, jlongArray input);
static void SWIG_JavaArrayArgoutUint (JNIEnv *jenv, jlong *jarr, unsigned int *carr, jlongArray input);
static jlongArray SWIG_JavaArrayOutUint (JNIEnv *jenv, unsigned int *result, jsize sz);


static int SWIG_JavaArrayInLong (JNIEnv *jenv, jint **jarr, long **carr, jintArray input);
static void SWIG_JavaArrayArgoutLong (JNIEnv *jenv, jint *jarr, long *carr, jintArray input);
static jintArray SWIG_JavaArrayOutLong (JNIEnv *jenv, long *result, jsize sz);


static int SWIG_JavaArrayInUlong (JNIEnv *jenv, jlong **jarr, unsigned long **carr, jlongArray input);
static void SWIG_JavaArrayArgoutUlong (JNIEnv *jenv, jlong *jarr, unsigned long *carr, jlongArray input);
static jlongArray SWIG_JavaArrayOutUlong (JNIEnv *jenv, unsigned long *result, jsize sz);


static int SWIG_JavaArrayInLonglong (JNIEnv *jenv, jlong **jarr, jlong **carr, jlongArray input);
static void SWIG_JavaArrayArgoutLonglong (JNIEnv *jenv, jlong *jarr, jlong *carr, jlongArray input);
static jlongArray SWIG_JavaArrayOutLonglong (JNIEnv *jenv, jlong *result, jsize sz);


static int SWIG_JavaArrayInFloat (JNIEnv *jenv, jfloat **jarr, float **carr, jfloatArray input);
static void SWIG_JavaArrayArgoutFloat (JNIEnv *jenv, jfloat *jarr, float *carr, jfloatArray input);
static jfloatArray SWIG_JavaArrayOutFloat (JNIEnv *jenv, float *result, jsize sz);


static int SWIG_JavaArrayInDouble (JNIEnv *jenv, jdouble **jarr, double **carr, jdoubleArray input);
static void SWIG_JavaArrayArgoutDouble (JNIEnv *jenv, jdouble *jarr, double *carr, jdoubleArray input);
static jdoubleArray SWIG_JavaArrayOutDouble (JNIEnv *jenv, double *result, jsize sz);


#else


/* signed char[] support */
static int SWIG_JavaArrayInSchar (JNIEnv *jenv, jbyte **jarr, signed char **carr, jbyteArray input) {
  int i;
  jsize sz;
  if (!input) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null array");
    return 0;
  }
  sz = (*jenv)->GetArrayLength(jenv, input);
  *jarr = (*jenv)->GetByteArrayElements(jenv, input, 0);
  if (!*jarr)
    return 0; 
  *carr = (signed char*) malloc(sz * sizeof(signed char)); 
  if (!*carr) {
    SWIG_JavaThrowException(jenv, SWIG_JavaOutOfMemoryError, "array memory allocation failed");
    return 0;
  }
  for (i=0; i<sz; i++)
    (*carr)[i] = (signed char)(*jarr)[i];
  return 1;
}

static void SWIG_JavaArrayArgoutSchar (JNIEnv *jenv, jbyte *jarr, signed char *carr, jbyteArray input) {
  int i;
  jsize sz = (*jenv)->GetArrayLength(jenv, input);
  for (i=0; i<sz; i++)
    jarr[i] = (jbyte)carr[i];
  (*jenv)->ReleaseByteArrayElements(jenv, input, jarr, 0);
}

static jbyteArray SWIG_JavaArrayOutSchar (JNIEnv *jenv, signed char *result, jsize sz) {
  jbyte *arr;
  int i;
  jbyteArray jresult = (*jenv)->NewByteArray(jenv, sz);
  if (!jresult)
    return NULL;
  arr = (*jenv)->GetByteArrayElements(jenv, jresult, 0);
  if (!arr)
    return NULL;
  for (i=0; i<sz; i++)
    arr[i] = (jbyte)result[i];
  (*jenv)->ReleaseByteArrayElements(jenv, jresult, arr, 0);
  return jresult;
}


/* unsigned char[] support */
static int SWIG_JavaArrayInUchar (JNIEnv *jenv, jshort **jarr, unsigned char **carr, jshortArray input) {
  int i;
  jsize sz;
  if (!input) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null array");
    return 0;
  }
  sz = (*jenv)->GetArrayLength(jenv, input);
  *jarr = (*jenv)->GetShortArrayElements(jenv, input, 0);
  if (!*jarr)
    return 0; 
  *carr = (unsigned char*) malloc(sz * sizeof(unsigned char)); 
  if (!*carr) {
    SWIG_JavaThrowException(jenv, SWIG_JavaOutOfMemoryError, "array memory allocation failed");
    return 0;
  }
  for (i=0; i<sz; i++)
    (*carr)[i] = (unsigned char)(*jarr)[i];
  return 1;
}

static void SWIG_JavaArrayArgoutUchar (JNIEnv *jenv, jshort *jarr, unsigned char *carr, jshortArray input) {
  int i;
  jsize sz = (*jenv)->GetArrayLength(jenv, input);
  for (i=0; i<sz; i++)
    jarr[i] = (jshort)carr[i];
  (*jenv)->ReleaseShortArrayElements(jenv, input, jarr, 0);
}

static jshortArray SWIG_JavaArrayOutUchar (JNIEnv *jenv, unsigned char *result, jsize sz) {
  jshort *arr;
  int i;
  jshortArray jresult = (*jenv)->NewShortArray(jenv, sz);
  if (!jresult)
    return NULL;
  arr = (*jenv)->GetShortArrayElements(jenv, jresult, 0);
  if (!arr)
    return NULL;
  for (i=0; i<sz; i++)
    arr[i] = (jshort)result[i];
  (*jenv)->ReleaseShortArrayElements(jenv, jresult, arr, 0);
  return jresult;
}


/* short[] support */
static int SWIG_JavaArrayInShort (JNIEnv *jenv, jshort **jarr, short **carr, jshortArray input) {
  int i;
  jsize sz;
  if (!input) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null array");
    return 0;
  }
  sz = (*jenv)->GetArrayLength(jenv, input);
  *jarr = (*jenv)->GetShortArrayElements(jenv, input, 0);
  if (!*jarr)
    return 0; 
  *carr = (short*) malloc(sz * sizeof(short)); 
  if (!*carr) {
    SWIG_JavaThrowException(jenv, SWIG_JavaOutOfMemoryError, "array memory allocation failed");
    return 0;
  }
  for (i=0; i<sz; i++)
    (*carr)[i] = (short)(*jarr)[i];
  return 1;
}

static void SWIG_JavaArrayArgoutShort (JNIEnv *jenv, jshort *jarr, short *carr, jshortArray input) {
  int i;
  jsize sz = (*jenv)->GetArrayLength(jenv, input);
  for (i=0; i<sz; i++)
    jarr[i] = (jshort)carr[i];
  (*jenv)->ReleaseShortArrayElements(jenv, input, jarr, 0);
}

static jshortArray SWIG_JavaArrayOutShort (JNIEnv *jenv, short *result, jsize sz) {
  jshort *arr;
  int i;
  jshortArray jresult = (*jenv)->NewShortArray(jenv, sz);
  if (!jresult)
    return NULL;
  arr = (*jenv)->GetShortArrayElements(jenv, jresult, 0);
  if (!arr)
    return NULL;
  for (i=0; i<sz; i++)
    arr[i] = (jshort)result[i];
  (*jenv)->ReleaseShortArrayElements(jenv, jresult, arr, 0);
  return jresult;
}


/* unsigned short[] support */
static int SWIG_JavaArrayInUshort (JNIEnv *jenv, jint **jarr, unsigned short **carr, jintArray input) {
  int i;
  jsize sz;
  if (!input) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null array");
    return 0;
  }
  sz = (*jenv)->GetArrayLength(jenv, input);
  *jarr = (*jenv)->GetIntArrayElements(jenv, input, 0);
  if (!*jarr)
    return 0; 
  *carr = (unsigned short*) malloc(sz * sizeof(unsigned short)); 
  if (!*carr) {
    SWIG_JavaThrowException(jenv, SWIG_JavaOutOfMemoryError, "array memory allocation failed");
    return 0;
  }
  for (i=0; i<sz; i++)
    (*carr)[i] = (unsigned short)(*jarr)[i];
  return 1;
}

static void SWIG_JavaArrayArgoutUshort (JNIEnv *jenv, jint *jarr, unsigned short *carr, jintArray input) {
  int i;
  jsize sz = (*jenv)->GetArrayLength(jenv, input);
  for (i=0; i<sz; i++)
    jarr[i] = (jint)carr[i];
  (*jenv)->ReleaseIntArrayElements(jenv, input, jarr, 0);
}

static jintArray SWIG_JavaArrayOutUshort (JNIEnv *jenv, unsigned short *result, jsize sz) {
  jint *arr;
  int i;
  jintArray jresult = (*jenv)->NewIntArray(jenv, sz);
  if (!jresult)
    return NULL;
  arr = (*jenv)->GetIntArrayElements(jenv, jresult, 0);
  if (!arr)
    return NULL;
  for (i=0; i<sz; i++)
    arr[i] = (jint)result[i];
  (*jenv)->ReleaseIntArrayElements(jenv, jresult, arr, 0);
  return jresult;
}


/* int[] support */
static int SWIG_JavaArrayInInt (JNIEnv *jenv, jint **jarr, int **carr, jintArray input) {
  int i;
  jsize sz;
  if (!input) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null array");
    return 0;
  }
  sz = (*jenv)->GetArrayLength(jenv, input);
  *jarr = (*jenv)->GetIntArrayElements(jenv, input, 0);
  if (!*jarr)
    return 0; 
  *carr = (int*) malloc(sz * sizeof(int)); 
  if (!*carr) {
    SWIG_JavaThrowException(jenv, SWIG_JavaOutOfMemoryError, "array memory allocation failed");
    return 0;
  }
  for (i=0; i<sz; i++)
    (*carr)[i] = (int)(*jarr)[i];
  return 1;
}

static void SWIG_JavaArrayArgoutInt (JNIEnv *jenv, jint *jarr, int *carr, jintArray input) {
  int i;
  jsize sz = (*jenv)->GetArrayLength(jenv, input);
  for (i=0; i<sz; i++)
    jarr[i] = (jint)carr[i];
  (*jenv)->ReleaseIntArrayElements(jenv, input, jarr, 0);
}

static jintArray SWIG_JavaArrayOutInt (JNIEnv *jenv, int *result, jsize sz) {
  jint *arr;
  int i;
  jintArray jresult = (*jenv)->NewIntArray(jenv, sz);
  if (!jresult)
    return NULL;
  arr = (*jenv)->GetIntArrayElements(jenv, jresult, 0);
  if (!arr)
    return NULL;
  for (i=0; i<sz; i++)
    arr[i] = (jint)result[i];
  (*jenv)->ReleaseIntArrayElements(jenv, jresult, arr, 0);
  return jresult;
}


/* unsigned int[] support */
static int SWIG_JavaArrayInUint (JNIEnv *jenv, jlong **jarr, unsigned int **carr, jlongArray input) {
  int i;
  jsize sz;
  if (!input) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null array");
    return 0;
  }
  sz = (*jenv)->GetArrayLength(jenv, input);
  *jarr = (*jenv)->GetLongArrayElements(jenv, input, 0);
  if (!*jarr)
    return 0; 
  *carr = (unsigned int*) malloc(sz * sizeof(unsigned int)); 
  if (!*carr) {
    SWIG_JavaThrowException(jenv, SWIG_JavaOutOfMemoryError, "array memory allocation failed");
    return 0;
  }
  for (i=0; i<sz; i++)
    (*carr)[i] = (unsigned int)(*jarr)[i];
  return 1;
}

static void SWIG_JavaArrayArgoutUint (JNIEnv *jenv, jlong *jarr, unsigned int *carr, jlongArray input) {
  int i;
  jsize sz = (*jenv)->GetArrayLength(jenv, input);
  for (i=0; i<sz; i++)
    jarr[i] = (jlong)carr[i];
  (*jenv)->ReleaseLongArrayElements(jenv, input, jarr, 0);
}

static jlongArray SWIG_JavaArrayOutUint (JNIEnv *jenv, unsigned int *result, jsize sz) {
  jlong *arr;
  int i;
  jlongArray jresult = (*jenv)->NewLongArray(jenv, sz);
  if (!jresult)
    return NULL;
  arr = (*jenv)->GetLongArrayElements(jenv, jresult, 0);
  if (!arr)
    return NULL;
  for (i=0; i<sz; i++)
    arr[i] = (jlong)result[i];
  (*jenv)->ReleaseLongArrayElements(jenv, jresult, arr, 0);
  return jresult;
}


/* long[] support */
static int SWIG_JavaArrayInLong (JNIEnv *jenv, jint **jarr, long **carr, jintArray input) {
  int i;
  jsize sz;
  if (!input) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null array");
    return 0;
  }
  sz = (*jenv)->GetArrayLength(jenv, input);
  *jarr = (*jenv)->GetIntArrayElements(jenv, input, 0);
  if (!*jarr)
    return 0; 
  *carr = (long*) malloc(sz * sizeof(long)); 
  if (!*carr) {
    SWIG_JavaThrowException(jenv, SWIG_JavaOutOfMemoryError, "array memory allocation failed");
    return 0;
  }
  for (i=0; i<sz; i++)
    (*carr)[i] = (long)(*jarr)[i];
  return 1;
}

static void SWIG_JavaArrayArgoutLong (JNIEnv *jenv, jint *jarr, long *carr, jintArray input) {
  int i;
  jsize sz = (*jenv)->GetArrayLength(jenv, input);
  for (i=0; i<sz; i++)
    jarr[i] = (jint)carr[i];
  (*jenv)->ReleaseIntArrayElements(jenv, input, jarr, 0);
}

static jintArray SWIG_JavaArrayOutLong (JNIEnv *jenv, long *result, jsize sz) {
  jint *arr;
  int i;
  jintArray jresult = (*jenv)->NewIntArray(jenv, sz);
  if (!jresult)
    return NULL;
  arr = (*jenv)->GetIntArrayElements(jenv, jresult, 0);
  if (!arr)
    return NULL;
  for (i=0; i<sz; i++)
    arr[i] = (jint)result[i];
  (*jenv)->ReleaseIntArrayElements(jenv, jresult, arr, 0);
  return jresult;
}


/* unsigned long[] support */
static int SWIG_JavaArrayInUlong (JNIEnv *jenv, jlong **jarr, unsigned long **carr, jlongArray input) {
  int i;
  jsize sz;
  if (!input) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null array");
    return 0;
  }
  sz = (*jenv)->GetArrayLength(jenv, input);
  *jarr = (*jenv)->GetLongArrayElements(jenv, input, 0);
  if (!*jarr)
    return 0; 
  *carr = (unsigned long*) malloc(sz * sizeof(unsigned long)); 
  if (!*carr) {
    SWIG_JavaThrowException(jenv, SWIG_JavaOutOfMemoryError, "array memory allocation failed");
    return 0;
  }
  for (i=0; i<sz; i++)
    (*carr)[i] = (unsigned long)(*jarr)[i];
  return 1;
}

static void SWIG_JavaArrayArgoutUlong (JNIEnv *jenv, jlong *jarr, unsigned long *carr, jlongArray input) {
  int i;
  jsize sz = (*jenv)->GetArrayLength(jenv, input);
  for (i=0; i<sz; i++)
    jarr[i] = (jlong)carr[i];
  (*jenv)->ReleaseLongArrayElements(jenv, input, jarr, 0);
}

static jlongArray SWIG_JavaArrayOutUlong (JNIEnv *jenv, unsigned long *result, jsize sz) {
  jlong *arr;
  int i;
  jlongArray jresult = (*jenv)->NewLongArray(jenv, sz);
  if (!jresult)
    return NULL;
  arr = (*jenv)->GetLongArrayElements(jenv, jresult, 0);
  if (!arr)
    return NULL;
  for (i=0; i<sz; i++)
    arr[i] = (jlong)result[i];
  (*jenv)->ReleaseLongArrayElements(jenv, jresult, arr, 0);
  return jresult;
}


/* jlong[] support */
static int SWIG_JavaArrayInLonglong (JNIEnv *jenv, jlong **jarr, jlong **carr, jlongArray input) {
  int i;
  jsize sz;
  if (!input) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null array");
    return 0;
  }
  sz = (*jenv)->GetArrayLength(jenv, input);
  *jarr = (*jenv)->GetLongArrayElements(jenv, input, 0);
  if (!*jarr)
    return 0; 
  *carr = (jlong*) malloc(sz * sizeof(jlong)); 
  if (!*carr) {
    SWIG_JavaThrowException(jenv, SWIG_JavaOutOfMemoryError, "array memory allocation failed");
    return 0;
  }
  for (i=0; i<sz; i++)
    (*carr)[i] = (jlong)(*jarr)[i];
  return 1;
}

static void SWIG_JavaArrayArgoutLonglong (JNIEnv *jenv, jlong *jarr, jlong *carr, jlongArray input) {
  int i;
  jsize sz = (*jenv)->GetArrayLength(jenv, input);
  for (i=0; i<sz; i++)
    jarr[i] = (jlong)carr[i];
  (*jenv)->ReleaseLongArrayElements(jenv, input, jarr, 0);
}

static jlongArray SWIG_JavaArrayOutLonglong (JNIEnv *jenv, jlong *result, jsize sz) {
  jlong *arr;
  int i;
  jlongArray jresult = (*jenv)->NewLongArray(jenv, sz);
  if (!jresult)
    return NULL;
  arr = (*jenv)->GetLongArrayElements(jenv, jresult, 0);
  if (!arr)
    return NULL;
  for (i=0; i<sz; i++)
    arr[i] = (jlong)result[i];
  (*jenv)->ReleaseLongArrayElements(jenv, jresult, arr, 0);
  return jresult;
}


/* float[] support */
static int SWIG_JavaArrayInFloat (JNIEnv *jenv, jfloat **jarr, float **carr, jfloatArray input) {
  int i;
  jsize sz;
  if (!input) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null array");
    return 0;
  }
  sz = (*jenv)->GetArrayLength(jenv, input);
  *jarr = (*jenv)->GetFloatArrayElements(jenv, input, 0);
  if (!*jarr)
    return 0; 
  *carr = (float*) malloc(sz * sizeof(float)); 
  if (!*carr) {
    SWIG_JavaThrowException(jenv, SWIG_JavaOutOfMemoryError, "array memory allocation failed");
    return 0;
  }
  for (i=0; i<sz; i++)
    (*carr)[i] = (float)(*jarr)[i];
  return 1;
}

static void SWIG_JavaArrayArgoutFloat (JNIEnv *jenv, jfloat *jarr, float *carr, jfloatArray input) {
  int i;
  jsize sz = (*jenv)->GetArrayLength(jenv, input);
  for (i=0; i<sz; i++)
    jarr[i] = (jfloat)carr[i];
  (*jenv)->ReleaseFloatArrayElements(jenv, input, jarr, 0);
}

static jfloatArray SWIG_JavaArrayOutFloat (JNIEnv *jenv, float *result, jsize sz) {
  jfloat *arr;
  int i;
  jfloatArray jresult = (*jenv)->NewFloatArray(jenv, sz);
  if (!jresult)
    return NULL;
  arr = (*jenv)->GetFloatArrayElements(jenv, jresult, 0);
  if (!arr)
    return NULL;
  for (i=0; i<sz; i++)
    arr[i] = (jfloat)result[i];
  (*jenv)->ReleaseFloatArrayElements(jenv, jresult, arr, 0);
  return jresult;
}


/* double[] support */
static int SWIG_JavaArrayInDouble (JNIEnv *jenv, jdouble **jarr, double **carr, jdoubleArray input) {
  int i;
  jsize sz;
  if (!input) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null array");
    return 0;
  }
  sz = (*jenv)->GetArrayLength(jenv, input);
  *jarr = (*jenv)->GetDoubleArrayElements(jenv, input, 0);
  if (!*jarr)
    return 0; 
  *carr = (double*) malloc(sz * sizeof(double)); 
  if (!*carr) {
    SWIG_JavaThrowException(jenv, SWIG_JavaOutOfMemoryError, "array memory allocation failed");
    return 0;
  }
  for (i=0; i<sz; i++)
    (*carr)[i] = (double)(*jarr)[i];
  return 1;
}

static void SWIG_JavaArrayArgoutDouble (JNIEnv *jenv, jdouble *jarr, double *carr, jdoubleArray input) {
  int i;
  jsize sz = (*jenv)->GetArrayLength(jenv, input);
  for (i=0; i<sz; i++)
    jarr[i] = (jdouble)carr[i];
  (*jenv)->ReleaseDoubleArrayElements(jenv, input, jarr, 0);
}

static jdoubleArray SWIG_JavaArrayOutDouble (JNIEnv *jenv, double *result, jsize sz) {
  jdouble *arr;
  int i;
  jdoubleArray jresult = (*jenv)->NewDoubleArray(jenv, sz);
  if (!jresult)
    return NULL;
  arr = (*jenv)->GetDoubleArrayElements(jenv, jresult, 0);
  if (!arr)
    return NULL;
  for (i=0; i<sz; i++)
    arr[i] = (jdouble)result[i];
  (*jenv)->ReleaseDoubleArrayElements(jenv, jresult, arr, 0);
  return jresult;
}


#endif

SWIGINTERN struct IdentifierBytes32_FFI *new_IdentifierBytes32_FFI(uint8_t identifierBytes[32]){
        struct IdentifierBytes32_FFI * identifierBytes32 = (struct IdentifierBytes32_FFI*)calloc(1, sizeof(struct IdentifierBytes32_FFI));
        identifierBytes32->_0 = (uint8_t (*)[32])calloc(1, sizeof(uint8_t[32]));
        memcpy(identifierBytes32->_0, identifierBytes, sizeof(uint8_t[32]));
        return identifierBytes32;
    }
SWIGINTERN void delete_IdentifierBytes32_FFI(struct IdentifierBytes32_FFI *self){
        free(self->_0); // Deallocate the memory when the object is destroyed
        free(self);
    }
SWIGINTERN enum Purpose_FFI IdentityPublicKeyV0_FFI_getPurpose(struct IdentityPublicKeyV0_FFI *self){
        return *self->purpose;
    }
SWIGINTERN void IdentityPublicKeyV0_FFI_setPurpose(struct IdentityPublicKeyV0_FFI *self,enum Purpose_FFI purpose){

    }
SWIGINTERN struct IdentityPublicKeyV0_FFI *IdentityV0_FFI_getPublicKey(struct IdentityV0_FFI *self,uint32_t index){
        return self->public_keys->values[index]->v0;
    }
SWIGINTERN struct IdentityPublicKeyV0_FFI *IdentityV0_FFI_getPublicKeyById(struct IdentityV0_FFI *self,uint32_t id){
        for (int i = 0; i < self->public_keys->count; ++i) {
            if(self->public_keys->keys[i]->_0 == id)
                return self->public_keys->values[i]->v0;
        }
        return NULL;
    }

#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT jint JNICALL Java_org_dash_sdk_exampleJNI_KeyType_1FFI_1ECDSA_1SECP256K1_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum KeyType_FFI result;
  
  (void)jenv;
  (void)jcls;
  result = (enum KeyType_FFI)KeyType_FFI_ECDSA_SECP256K1;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_dash_sdk_exampleJNI_KeyType_1FFI_1BLS12_1381_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum KeyType_FFI result;
  
  (void)jenv;
  (void)jcls;
  result = (enum KeyType_FFI)KeyType_FFI_BLS12_381;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_dash_sdk_exampleJNI_KeyType_1FFI_1ECDSA_1HASH160_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum KeyType_FFI result;
  
  (void)jenv;
  (void)jcls;
  result = (enum KeyType_FFI)KeyType_FFI_ECDSA_HASH160;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_dash_sdk_exampleJNI_KeyType_1FFI_1BIP13_1SCRIPT_1HASH_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum KeyType_FFI result;
  
  (void)jenv;
  (void)jcls;
  result = (enum KeyType_FFI)KeyType_FFI_BIP13_SCRIPT_HASH;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_dash_sdk_exampleJNI_KeyType_1FFI_1EDDSA_125519_1HASH160_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum KeyType_FFI result;
  
  (void)jenv;
  (void)jcls;
  result = (enum KeyType_FFI)KeyType_FFI_EDDSA_25519_HASH160;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_dash_sdk_exampleJNI_Purpose_1FFI_1AUTHENTICATION_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum Purpose_FFI result;
  
  (void)jenv;
  (void)jcls;
  result = (enum Purpose_FFI)Purpose_FFI_AUTHENTICATION;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_dash_sdk_exampleJNI_Purpose_1FFI_1ENCRYPTION_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum Purpose_FFI result;
  
  (void)jenv;
  (void)jcls;
  result = (enum Purpose_FFI)Purpose_FFI_ENCRYPTION;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_dash_sdk_exampleJNI_Purpose_1FFI_1DECRYPTION_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum Purpose_FFI result;
  
  (void)jenv;
  (void)jcls;
  result = (enum Purpose_FFI)Purpose_FFI_DECRYPTION;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_dash_sdk_exampleJNI_Purpose_1FFI_1WITHDRAW_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum Purpose_FFI result;
  
  (void)jenv;
  (void)jcls;
  result = (enum Purpose_FFI)Purpose_FFI_WITHDRAW;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_dash_sdk_exampleJNI_Purpose_1FFI_1SYSTEM_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum Purpose_FFI result;
  
  (void)jenv;
  (void)jcls;
  result = (enum Purpose_FFI)Purpose_FFI_SYSTEM;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_dash_sdk_exampleJNI_Purpose_1FFI_1VOTING_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum Purpose_FFI result;
  
  (void)jenv;
  (void)jcls;
  result = (enum Purpose_FFI)Purpose_FFI_VOTING;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_dash_sdk_exampleJNI_SecurityLevel_1FFI_1MASTER_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum SecurityLevel_FFI result;
  
  (void)jenv;
  (void)jcls;
  result = (enum SecurityLevel_FFI)SecurityLevel_FFI_MASTER;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_dash_sdk_exampleJNI_SecurityLevel_1FFI_1CRITICAL_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum SecurityLevel_FFI result;
  
  (void)jenv;
  (void)jcls;
  result = (enum SecurityLevel_FFI)SecurityLevel_FFI_CRITICAL;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_dash_sdk_exampleJNI_SecurityLevel_1FFI_1HIGH_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum SecurityLevel_FFI result;
  
  (void)jenv;
  (void)jcls;
  result = (enum SecurityLevel_FFI)SecurityLevel_FFI_HIGH;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_dash_sdk_exampleJNI_SecurityLevel_1FFI_1MEDIUM_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum SecurityLevel_FFI result;
  
  (void)jenv;
  (void)jcls;
  result = (enum SecurityLevel_FFI)SecurityLevel_FFI_MEDIUM;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_dash_sdk_exampleJNI_IdentifierBytes32_1_10_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jbyteArray jarg2) {
  struct IdentifierBytes32_FFI *arg1 = (struct IdentifierBytes32_FFI *) 0 ;
  uint8_t (*arg2)[32] = (uint8_t (*)[32]) 0 ;
  uint8_t *byteArray2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct IdentifierBytes32_FFI **)&jarg1; 
  {
    //arg2 = (uint8_t (*)[32]) JCALL2(GetByteArrayElements, jenv, jarg2, 0);
    if (!jarg2) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null array");
      return ;
    }
    const jsize sz = (*jenv)->GetArrayLength(jenv, jarg2);
    jbyte* const jarr = (*jenv)->GetByteArrayElements(jenv, jarg2, 0);
    if (!jarr) return ;
    byteArray2 = calloc(1, 32); // this is a memory leak?
    memcpy(byteArray2, jarr, sz);
    (*jenv)->ReleaseByteArrayElements(jenv, jarg2, jarr, JNI_ABORT);
    arg2 = (uint8_t (*) [32])byteArray2;
  }
  if (arg1) (arg1)->_0 = (uint8_t (*)[32])arg2;
  {
    //JCALL3(ReleaseByteArrayElements, jenv, jarg2, (jbyte *) *arg2, 0);
  }
  
}


SWIGEXPORT jbyteArray JNICALL Java_org_dash_sdk_exampleJNI_IdentifierBytes32_1_10_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jbyteArray jresult = 0 ;
  struct IdentifierBytes32_FFI *arg1 = (struct IdentifierBytes32_FFI *) 0 ;
  uint8_t (*result)[32] = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct IdentifierBytes32_FFI **)&jarg1; 
  result = (uint8_t (*)[32]) ((arg1)->_0);
  {
    jresult = (*jenv)->NewByteArray(jenv, 32);
    (*jenv)->SetByteArrayRegion(jenv, jresult, 0, 32, (jbyte *)(*result));
  }
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_dash_sdk_exampleJNI_new_1IdentifierBytes32(JNIEnv *jenv, jclass jcls, jshortArray jarg1) {
  jlong jresult = 0 ;
  uint8_t *arg1 ;
  jshort *jarr1 ;
  struct IdentifierBytes32_FFI *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  if (jarg1 && (*jenv)->GetArrayLength(jenv, jarg1) != 32) {
    SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "incorrect array size");
    return 0;
  }
  if (!SWIG_JavaArrayInUchar(jenv, &jarr1, (unsigned char **)&arg1, jarg1)) return 0; 
  result = (struct IdentifierBytes32_FFI *)new_IdentifierBytes32_FFI(arg1);
  *(struct IdentifierBytes32_FFI **)&jresult = result; 
  SWIG_JavaArrayArgoutUchar(jenv, jarr1, (unsigned char *)arg1, jarg1); 
  free(arg1); 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_dash_sdk_exampleJNI_delete_1IdentifierBytes32(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct IdentifierBytes32_FFI *arg1 = (struct IdentifierBytes32_FFI *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct IdentifierBytes32_FFI **)&jarg1; 
  delete_IdentifierBytes32_FFI(arg1);
}


SWIGEXPORT void JNICALL Java_org_dash_sdk_exampleJNI_Identifier_1_10_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  struct Identifier_FFI *arg1 = (struct Identifier_FFI *) 0 ;
  struct IdentifierBytes32_FFI *arg2 = (struct IdentifierBytes32_FFI *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(struct Identifier_FFI **)&jarg1; 
  arg2 = *(struct IdentifierBytes32_FFI **)&jarg2; 
  if (arg1) (arg1)->_0 = arg2;
}


SWIGEXPORT jlong JNICALL Java_org_dash_sdk_exampleJNI_Identifier_1_10_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct Identifier_FFI *arg1 = (struct Identifier_FFI *) 0 ;
  struct IdentifierBytes32_FFI *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct Identifier_FFI **)&jarg1; 
  result = (struct IdentifierBytes32_FFI *) ((arg1)->_0);
  *(struct IdentifierBytes32_FFI **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_dash_sdk_exampleJNI_new_1Identifier(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct Identifier_FFI *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct Identifier_FFI *)calloc(1, sizeof(struct Identifier_FFI));
  *(struct Identifier_FFI **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_dash_sdk_exampleJNI_delete_1Identifier(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct Identifier_FFI *arg1 = (struct Identifier_FFI *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct Identifier_FFI **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void JNICALL Java_org_dash_sdk_exampleJNI_KeyID_1_10_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct KeyID_FFI *arg1 = (struct KeyID_FFI *) 0 ;
  uint32_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct KeyID_FFI **)&jarg1; 
  arg2 = (uint32_t)jarg2; 
  if (arg1) (arg1)->_0 = arg2;
}


SWIGEXPORT jlong JNICALL Java_org_dash_sdk_exampleJNI_KeyID_1_10_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct KeyID_FFI *arg1 = (struct KeyID_FFI *) 0 ;
  uint32_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct KeyID_FFI **)&jarg1; 
  result = (uint32_t) ((arg1)->_0);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_dash_sdk_exampleJNI_new_1KeyID(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct KeyID_FFI *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct KeyID_FFI *)calloc(1, sizeof(struct KeyID_FFI));
  *(struct KeyID_FFI **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_dash_sdk_exampleJNI_delete_1KeyID(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct KeyID_FFI *arg1 = (struct KeyID_FFI *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct KeyID_FFI **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void JNICALL Java_org_dash_sdk_exampleJNI_ContractBounds_1FFI_1SingleContractDocumentType_1Body_1_10_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  struct ContractBounds_FFI_SingleContractDocumentType_Body *arg1 = (struct ContractBounds_FFI_SingleContractDocumentType_Body *) 0 ;
  struct Identifier_FFI *arg2 = (struct Identifier_FFI *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(struct ContractBounds_FFI_SingleContractDocumentType_Body **)&jarg1; 
  arg2 = *(struct Identifier_FFI **)&jarg2; 
  if (arg1) (arg1)->_0 = arg2;
}


SWIGEXPORT jlong JNICALL Java_org_dash_sdk_exampleJNI_ContractBounds_1FFI_1SingleContractDocumentType_1Body_1_10_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct ContractBounds_FFI_SingleContractDocumentType_Body *arg1 = (struct ContractBounds_FFI_SingleContractDocumentType_Body *) 0 ;
  struct Identifier_FFI *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct ContractBounds_FFI_SingleContractDocumentType_Body **)&jarg1; 
  result = (struct Identifier_FFI *) ((arg1)->_0);
  *(struct Identifier_FFI **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_dash_sdk_exampleJNI_ContractBounds_1FFI_1SingleContractDocumentType_1Body_1_11_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  struct ContractBounds_FFI_SingleContractDocumentType_Body *arg1 = (struct ContractBounds_FFI_SingleContractDocumentType_Body *) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct ContractBounds_FFI_SingleContractDocumentType_Body **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  {
    free(arg1->_1);
    if (arg2) {
      arg1->_1 = (char *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->_1, (const char *)arg2);
    } else {
      arg1->_1 = 0;
    }
  }
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_org_dash_sdk_exampleJNI_ContractBounds_1FFI_1SingleContractDocumentType_1Body_1_11_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  struct ContractBounds_FFI_SingleContractDocumentType_Body *arg1 = (struct ContractBounds_FFI_SingleContractDocumentType_Body *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct ContractBounds_FFI_SingleContractDocumentType_Body **)&jarg1; 
  result = (char *) ((arg1)->_1);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_dash_sdk_exampleJNI_new_1ContractBounds_1FFI_1SingleContractDocumentType_1Body(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct ContractBounds_FFI_SingleContractDocumentType_Body *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct ContractBounds_FFI_SingleContractDocumentType_Body *)calloc(1, sizeof(struct ContractBounds_FFI_SingleContractDocumentType_Body));
  *(struct ContractBounds_FFI_SingleContractDocumentType_Body **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_dash_sdk_exampleJNI_delete_1ContractBounds_1FFI_1SingleContractDocumentType_1Body(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct ContractBounds_FFI_SingleContractDocumentType_Body *arg1 = (struct ContractBounds_FFI_SingleContractDocumentType_Body *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct ContractBounds_FFI_SingleContractDocumentType_Body **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void JNICALL Java_org_dash_sdk_exampleJNI_ContractBounds_1FFI_1tag_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct ContractBounds_FFI *arg1 = (struct ContractBounds_FFI *) 0 ;
  enum ContractBounds_FFI_Tag arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct ContractBounds_FFI **)&jarg1; 
  arg2 = (enum ContractBounds_FFI_Tag)jarg2; 
  if (arg1) (arg1)->tag = arg2;
}


SWIGEXPORT jint JNICALL Java_org_dash_sdk_exampleJNI_ContractBounds_1FFI_1tag_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct ContractBounds_FFI *arg1 = (struct ContractBounds_FFI *) 0 ;
  enum ContractBounds_FFI_Tag result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct ContractBounds_FFI **)&jarg1; 
  result = (enum ContractBounds_FFI_Tag) ((arg1)->tag);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_dash_sdk_exampleJNI_ContractBounds_1FFI_1single_1contract_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  struct ContractBounds_FFI *arg1 = (struct ContractBounds_FFI *) 0 ;
  struct Identifier_FFI *arg2 = (struct Identifier_FFI *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(struct ContractBounds_FFI **)&jarg1; 
  arg2 = *(struct Identifier_FFI **)&jarg2; 
  if (arg1) (arg1)->single_contract = arg2;
}


SWIGEXPORT jlong JNICALL Java_org_dash_sdk_exampleJNI_ContractBounds_1FFI_1single_1contract_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct ContractBounds_FFI *arg1 = (struct ContractBounds_FFI *) 0 ;
  struct Identifier_FFI *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct ContractBounds_FFI **)&jarg1; 
  result = (struct Identifier_FFI *) ((arg1)->single_contract);
  *(struct Identifier_FFI **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_dash_sdk_exampleJNI_ContractBounds_1FFI_1single_1contract_1document_1type_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  struct ContractBounds_FFI *arg1 = (struct ContractBounds_FFI *) 0 ;
  struct ContractBounds_FFI_SingleContractDocumentType_Body *arg2 = (struct ContractBounds_FFI_SingleContractDocumentType_Body *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(struct ContractBounds_FFI **)&jarg1; 
  arg2 = *(struct ContractBounds_FFI_SingleContractDocumentType_Body **)&jarg2; 
  if (arg1) (arg1)->single_contract_document_type = *arg2;
}


SWIGEXPORT jlong JNICALL Java_org_dash_sdk_exampleJNI_ContractBounds_1FFI_1single_1contract_1document_1type_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct ContractBounds_FFI *arg1 = (struct ContractBounds_FFI *) 0 ;
  struct ContractBounds_FFI_SingleContractDocumentType_Body *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct ContractBounds_FFI **)&jarg1; 
  result = (struct ContractBounds_FFI_SingleContractDocumentType_Body *)& ((arg1)->single_contract_document_type);
  *(struct ContractBounds_FFI_SingleContractDocumentType_Body **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_dash_sdk_exampleJNI_new_1ContractBounds_1FFI(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct ContractBounds_FFI *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct ContractBounds_FFI *)calloc(1, sizeof(struct ContractBounds_FFI));
  *(struct ContractBounds_FFI **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_dash_sdk_exampleJNI_delete_1ContractBounds_1FFI(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct ContractBounds_FFI *arg1 = (struct ContractBounds_FFI *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct ContractBounds_FFI **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void JNICALL Java_org_dash_sdk_exampleJNI_Vec_1u8_1FFI_1count_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct Vec_u8_FFI *arg1 = (struct Vec_u8_FFI *) 0 ;
  uintptr_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct Vec_u8_FFI **)&jarg1; 
  arg2 = (uintptr_t)jarg2; 
  if (arg1) (arg1)->count = arg2;
}


SWIGEXPORT jlong JNICALL Java_org_dash_sdk_exampleJNI_Vec_1u8_1FFI_1count_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct Vec_u8_FFI *arg1 = (struct Vec_u8_FFI *) 0 ;
  uintptr_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct Vec_u8_FFI **)&jarg1; 
  result = (uintptr_t) ((arg1)->count);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_dash_sdk_exampleJNI_Vec_1u8_1FFI_1values_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct Vec_u8_FFI *arg1 = (struct Vec_u8_FFI *) 0 ;
  uint8_t *arg2 = (uint8_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct Vec_u8_FFI **)&jarg1; 
  arg2 = *(uint8_t **)&jarg2; 
  if (arg1) (arg1)->values = arg2;
}


SWIGEXPORT jlong JNICALL Java_org_dash_sdk_exampleJNI_Vec_1u8_1FFI_1values_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct Vec_u8_FFI *arg1 = (struct Vec_u8_FFI *) 0 ;
  uint8_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct Vec_u8_FFI **)&jarg1; 
  result = (uint8_t *) ((arg1)->values);
  *(uint8_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_dash_sdk_exampleJNI_new_1Vec_1u8_1FFI(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct Vec_u8_FFI *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct Vec_u8_FFI *)calloc(1, sizeof(struct Vec_u8_FFI));
  *(struct Vec_u8_FFI **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_dash_sdk_exampleJNI_delete_1Vec_1u8_1FFI(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct Vec_u8_FFI *arg1 = (struct Vec_u8_FFI *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct Vec_u8_FFI **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void JNICALL Java_org_dash_sdk_exampleJNI_BinaryData_1_10_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  struct BinaryData_FFI *arg1 = (struct BinaryData_FFI *) 0 ;
  struct Vec_u8_FFI *arg2 = (struct Vec_u8_FFI *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(struct BinaryData_FFI **)&jarg1; 
  arg2 = *(struct Vec_u8_FFI **)&jarg2; 
  if (arg1) (arg1)->_0 = arg2;
}


SWIGEXPORT jlong JNICALL Java_org_dash_sdk_exampleJNI_BinaryData_1_10_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct BinaryData_FFI *arg1 = (struct BinaryData_FFI *) 0 ;
  struct Vec_u8_FFI *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct BinaryData_FFI **)&jarg1; 
  result = (struct Vec_u8_FFI *) ((arg1)->_0);
  *(struct Vec_u8_FFI **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_dash_sdk_exampleJNI_new_1BinaryData(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct BinaryData_FFI *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct BinaryData_FFI *)calloc(1, sizeof(struct BinaryData_FFI));
  *(struct BinaryData_FFI **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_dash_sdk_exampleJNI_delete_1BinaryData(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct BinaryData_FFI *arg1 = (struct BinaryData_FFI *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct BinaryData_FFI **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void JNICALL Java_org_dash_sdk_exampleJNI_TimestampMillis_1FFI_1_10_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jobject jarg2) {
  struct TimestampMillis_FFI *arg1 = (struct TimestampMillis_FFI *) 0 ;
  uint64_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct TimestampMillis_FFI **)&jarg1; 
  {
    jclass clazz;
    jmethodID mid;
    jbyteArray ba;
    jbyte* bae;
    jsize sz;
    int i;
    
    if (!jarg2) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "BigInteger null");
      return ;
    }
    clazz = (*jenv)->GetObjectClass(jenv, jarg2);
    mid = (*jenv)->GetMethodID(jenv, clazz, "toByteArray", "()[B");
    ba = (jbyteArray)(*jenv)->CallObjectMethod(jenv, jarg2, mid);
    bae = (*jenv)->GetByteArrayElements(jenv, ba, 0);
    sz = (*jenv)->GetArrayLength(jenv, ba);
    arg2 = 0;
    if (sz > 0) {
      arg2 = (uint64_t)(signed char)bae[0];
      for(i=1; i<sz; i++) {
        arg2 = (arg2 << 8) | (uint64_t)(unsigned char)bae[i];
      }
    }
    (*jenv)->ReleaseByteArrayElements(jenv, ba, bae, 0);
  }
  if (arg1) (arg1)->_0 = arg2;
}


SWIGEXPORT jobject JNICALL Java_org_dash_sdk_exampleJNI_TimestampMillis_1FFI_1_10_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jobject jresult = 0 ;
  struct TimestampMillis_FFI *arg1 = (struct TimestampMillis_FFI *) 0 ;
  uint64_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct TimestampMillis_FFI **)&jarg1; 
  result = (uint64_t) ((arg1)->_0);
  {
    jbyteArray ba = (*jenv)->NewByteArray(jenv, 9);
    jbyte* bae = (*jenv)->GetByteArrayElements(jenv, ba, 0);
    jclass clazz = (*jenv)->FindClass(jenv, "java/math/BigInteger");
    jmethodID mid = (*jenv)->GetMethodID(jenv, clazz, "<init>", "([B)V");
    jobject bigint;
    int i;
    
    bae[0] = 0;
    for(i=1; i<9; i++ ) {
      bae[i] = (jbyte)(result>>8*(8-i));
    }
    
    (*jenv)->ReleaseByteArrayElements(jenv, ba, bae, 0);
    bigint = (*jenv)->NewObject(jenv, clazz, mid, ba);
    (*jenv)->DeleteLocalRef(jenv, ba);
    jresult = bigint;
  }
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_dash_sdk_exampleJNI_new_1TimestampMillis_1FFI(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct TimestampMillis_FFI *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct TimestampMillis_FFI *)calloc(1, sizeof(struct TimestampMillis_FFI));
  *(struct TimestampMillis_FFI **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_dash_sdk_exampleJNI_delete_1TimestampMillis_1FFI(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct TimestampMillis_FFI *arg1 = (struct TimestampMillis_FFI *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct TimestampMillis_FFI **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void JNICALL Java_org_dash_sdk_exampleJNI_IdentityPublicKeyV0_1id_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  struct IdentityPublicKeyV0_FFI *arg1 = (struct IdentityPublicKeyV0_FFI *) 0 ;
  struct KeyID_FFI *arg2 = (struct KeyID_FFI *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(struct IdentityPublicKeyV0_FFI **)&jarg1; 
  arg2 = *(struct KeyID_FFI **)&jarg2; 
  if (arg1) (arg1)->id = arg2;
}


SWIGEXPORT jlong JNICALL Java_org_dash_sdk_exampleJNI_IdentityPublicKeyV0_1id_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct IdentityPublicKeyV0_FFI *arg1 = (struct IdentityPublicKeyV0_FFI *) 0 ;
  struct KeyID_FFI *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct IdentityPublicKeyV0_FFI **)&jarg1; 
  result = (struct KeyID_FFI *) ((arg1)->id);
  *(struct KeyID_FFI **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_dash_sdk_exampleJNI_IdentityPublicKeyV0_1security_1level_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct IdentityPublicKeyV0_FFI *arg1 = (struct IdentityPublicKeyV0_FFI *) 0 ;
  enum SecurityLevel_FFI *arg2 = (enum SecurityLevel_FFI *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct IdentityPublicKeyV0_FFI **)&jarg1; 
  arg2 = *(enum SecurityLevel_FFI **)&jarg2; 
  if (arg1) (arg1)->security_level = arg2;
}


SWIGEXPORT jlong JNICALL Java_org_dash_sdk_exampleJNI_IdentityPublicKeyV0_1security_1level_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct IdentityPublicKeyV0_FFI *arg1 = (struct IdentityPublicKeyV0_FFI *) 0 ;
  enum SecurityLevel_FFI *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct IdentityPublicKeyV0_FFI **)&jarg1; 
  result = (enum SecurityLevel_FFI *) ((arg1)->security_level);
  *(enum SecurityLevel_FFI **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_dash_sdk_exampleJNI_IdentityPublicKeyV0_1contract_1bounds_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  struct IdentityPublicKeyV0_FFI *arg1 = (struct IdentityPublicKeyV0_FFI *) 0 ;
  struct ContractBounds_FFI *arg2 = (struct ContractBounds_FFI *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(struct IdentityPublicKeyV0_FFI **)&jarg1; 
  arg2 = *(struct ContractBounds_FFI **)&jarg2; 
  if (arg1) (arg1)->contract_bounds = arg2;
}


SWIGEXPORT jlong JNICALL Java_org_dash_sdk_exampleJNI_IdentityPublicKeyV0_1contract_1bounds_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct IdentityPublicKeyV0_FFI *arg1 = (struct IdentityPublicKeyV0_FFI *) 0 ;
  struct ContractBounds_FFI *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct IdentityPublicKeyV0_FFI **)&jarg1; 
  result = (struct ContractBounds_FFI *) ((arg1)->contract_bounds);
  *(struct ContractBounds_FFI **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_dash_sdk_exampleJNI_IdentityPublicKeyV0_1key_1type_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct IdentityPublicKeyV0_FFI *arg1 = (struct IdentityPublicKeyV0_FFI *) 0 ;
  enum KeyType_FFI *arg2 = (enum KeyType_FFI *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct IdentityPublicKeyV0_FFI **)&jarg1; 
  arg2 = *(enum KeyType_FFI **)&jarg2; 
  if (arg1) (arg1)->key_type = arg2;
}


SWIGEXPORT jlong JNICALL Java_org_dash_sdk_exampleJNI_IdentityPublicKeyV0_1key_1type_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct IdentityPublicKeyV0_FFI *arg1 = (struct IdentityPublicKeyV0_FFI *) 0 ;
  enum KeyType_FFI *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct IdentityPublicKeyV0_FFI **)&jarg1; 
  result = (enum KeyType_FFI *) ((arg1)->key_type);
  *(enum KeyType_FFI **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_dash_sdk_exampleJNI_IdentityPublicKeyV0_1read_1only_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jboolean jarg2) {
  struct IdentityPublicKeyV0_FFI *arg1 = (struct IdentityPublicKeyV0_FFI *) 0 ;
  bool arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct IdentityPublicKeyV0_FFI **)&jarg1; 
  arg2 = jarg2 ? true : false; 
  if (arg1) (arg1)->read_only = arg2;
}


SWIGEXPORT jboolean JNICALL Java_org_dash_sdk_exampleJNI_IdentityPublicKeyV0_1read_1only_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jboolean jresult = 0 ;
  struct IdentityPublicKeyV0_FFI *arg1 = (struct IdentityPublicKeyV0_FFI *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct IdentityPublicKeyV0_FFI **)&jarg1; 
  result = (bool) ((arg1)->read_only);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_dash_sdk_exampleJNI_IdentityPublicKeyV0_1data_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  struct IdentityPublicKeyV0_FFI *arg1 = (struct IdentityPublicKeyV0_FFI *) 0 ;
  struct BinaryData_FFI *arg2 = (struct BinaryData_FFI *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(struct IdentityPublicKeyV0_FFI **)&jarg1; 
  arg2 = *(struct BinaryData_FFI **)&jarg2; 
  if (arg1) (arg1)->data = arg2;
}


SWIGEXPORT jlong JNICALL Java_org_dash_sdk_exampleJNI_IdentityPublicKeyV0_1data_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct IdentityPublicKeyV0_FFI *arg1 = (struct IdentityPublicKeyV0_FFI *) 0 ;
  struct BinaryData_FFI *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct IdentityPublicKeyV0_FFI **)&jarg1; 
  result = (struct BinaryData_FFI *) ((arg1)->data);
  *(struct BinaryData_FFI **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_dash_sdk_exampleJNI_IdentityPublicKeyV0_1disabled_1at_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  struct IdentityPublicKeyV0_FFI *arg1 = (struct IdentityPublicKeyV0_FFI *) 0 ;
  struct TimestampMillis_FFI *arg2 = (struct TimestampMillis_FFI *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(struct IdentityPublicKeyV0_FFI **)&jarg1; 
  arg2 = *(struct TimestampMillis_FFI **)&jarg2; 
  if (arg1) (arg1)->disabled_at = arg2;
}


SWIGEXPORT jlong JNICALL Java_org_dash_sdk_exampleJNI_IdentityPublicKeyV0_1disabled_1at_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct IdentityPublicKeyV0_FFI *arg1 = (struct IdentityPublicKeyV0_FFI *) 0 ;
  struct TimestampMillis_FFI *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct IdentityPublicKeyV0_FFI **)&jarg1; 
  result = (struct TimestampMillis_FFI *) ((arg1)->disabled_at);
  *(struct TimestampMillis_FFI **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_dash_sdk_exampleJNI_IdentityPublicKeyV0_1getPurpose(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct IdentityPublicKeyV0_FFI *arg1 = (struct IdentityPublicKeyV0_FFI *) 0 ;
  enum Purpose_FFI result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct IdentityPublicKeyV0_FFI **)&jarg1; 
  result = (enum Purpose_FFI)IdentityPublicKeyV0_FFI_getPurpose(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_dash_sdk_exampleJNI_IdentityPublicKeyV0_1setPurpose(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct IdentityPublicKeyV0_FFI *arg1 = (struct IdentityPublicKeyV0_FFI *) 0 ;
  enum Purpose_FFI arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct IdentityPublicKeyV0_FFI **)&jarg1; 
  arg2 = (enum Purpose_FFI)jarg2; 
  IdentityPublicKeyV0_FFI_setPurpose(arg1,arg2);
}


SWIGEXPORT jlong JNICALL Java_org_dash_sdk_exampleJNI_new_1IdentityPublicKeyV0(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct IdentityPublicKeyV0_FFI *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct IdentityPublicKeyV0_FFI *)calloc(1, sizeof(struct IdentityPublicKeyV0_FFI));
  *(struct IdentityPublicKeyV0_FFI **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_dash_sdk_exampleJNI_delete_1IdentityPublicKeyV0(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct IdentityPublicKeyV0_FFI *arg1 = (struct IdentityPublicKeyV0_FFI *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct IdentityPublicKeyV0_FFI **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void JNICALL Java_org_dash_sdk_exampleJNI_IdentityPublicKey_1tag_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct IdentityPublicKey_FFI *arg1 = (struct IdentityPublicKey_FFI *) 0 ;
  enum IdentityPublicKey_FFI_Tag arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct IdentityPublicKey_FFI **)&jarg1; 
  arg2 = (enum IdentityPublicKey_FFI_Tag)jarg2; 
  if (arg1) (arg1)->tag = arg2;
}


SWIGEXPORT jint JNICALL Java_org_dash_sdk_exampleJNI_IdentityPublicKey_1tag_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct IdentityPublicKey_FFI *arg1 = (struct IdentityPublicKey_FFI *) 0 ;
  enum IdentityPublicKey_FFI_Tag result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct IdentityPublicKey_FFI **)&jarg1; 
  result = (enum IdentityPublicKey_FFI_Tag) ((arg1)->tag);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_dash_sdk_exampleJNI_IdentityPublicKey_1v0_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  struct IdentityPublicKey_FFI *arg1 = (struct IdentityPublicKey_FFI *) 0 ;
  struct IdentityPublicKeyV0_FFI *arg2 = (struct IdentityPublicKeyV0_FFI *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(struct IdentityPublicKey_FFI **)&jarg1; 
  arg2 = *(struct IdentityPublicKeyV0_FFI **)&jarg2; 
  if (arg1) (arg1)->v0 = arg2;
}


SWIGEXPORT jlong JNICALL Java_org_dash_sdk_exampleJNI_IdentityPublicKey_1v0_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct IdentityPublicKey_FFI *arg1 = (struct IdentityPublicKey_FFI *) 0 ;
  struct IdentityPublicKeyV0_FFI *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct IdentityPublicKey_FFI **)&jarg1; 
  result = (struct IdentityPublicKeyV0_FFI *) ((arg1)->v0);
  *(struct IdentityPublicKeyV0_FFI **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_dash_sdk_exampleJNI_new_1IdentityPublicKey(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct IdentityPublicKey_FFI *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct IdentityPublicKey_FFI *)calloc(1, sizeof(struct IdentityPublicKey_FFI));
  *(struct IdentityPublicKey_FFI **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_dash_sdk_exampleJNI_delete_1IdentityPublicKey(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct IdentityPublicKey_FFI *arg1 = (struct IdentityPublicKey_FFI *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct IdentityPublicKey_FFI **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void JNICALL Java_org_dash_sdk_exampleJNI_std_1collections_1Map_1keys_1crate_1nested_1KeyID_1values_1crate_1nested_1IdentityPublicKey_1FFI_1count_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct std_collections_Map_keys_crate_nested_KeyID_values_crate_nested_IdentityPublicKey_FFI *arg1 = (struct std_collections_Map_keys_crate_nested_KeyID_values_crate_nested_IdentityPublicKey_FFI *) 0 ;
  uintptr_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct std_collections_Map_keys_crate_nested_KeyID_values_crate_nested_IdentityPublicKey_FFI **)&jarg1; 
  arg2 = (uintptr_t)jarg2; 
  if (arg1) (arg1)->count = arg2;
}


SWIGEXPORT jlong JNICALL Java_org_dash_sdk_exampleJNI_std_1collections_1Map_1keys_1crate_1nested_1KeyID_1values_1crate_1nested_1IdentityPublicKey_1FFI_1count_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct std_collections_Map_keys_crate_nested_KeyID_values_crate_nested_IdentityPublicKey_FFI *arg1 = (struct std_collections_Map_keys_crate_nested_KeyID_values_crate_nested_IdentityPublicKey_FFI *) 0 ;
  uintptr_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct std_collections_Map_keys_crate_nested_KeyID_values_crate_nested_IdentityPublicKey_FFI **)&jarg1; 
  result = (uintptr_t) ((arg1)->count);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_dash_sdk_exampleJNI_std_1collections_1Map_1keys_1crate_1nested_1KeyID_1values_1crate_1nested_1IdentityPublicKey_1FFI_1keys_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct std_collections_Map_keys_crate_nested_KeyID_values_crate_nested_IdentityPublicKey_FFI *arg1 = (struct std_collections_Map_keys_crate_nested_KeyID_values_crate_nested_IdentityPublicKey_FFI *) 0 ;
  struct KeyID_FFI **arg2 = (struct KeyID_FFI **) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct std_collections_Map_keys_crate_nested_KeyID_values_crate_nested_IdentityPublicKey_FFI **)&jarg1; 
  arg2 = *(struct KeyID_FFI ***)&jarg2; 
  if (arg1) (arg1)->keys = arg2;
}


SWIGEXPORT jlong JNICALL Java_org_dash_sdk_exampleJNI_std_1collections_1Map_1keys_1crate_1nested_1KeyID_1values_1crate_1nested_1IdentityPublicKey_1FFI_1keys_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct std_collections_Map_keys_crate_nested_KeyID_values_crate_nested_IdentityPublicKey_FFI *arg1 = (struct std_collections_Map_keys_crate_nested_KeyID_values_crate_nested_IdentityPublicKey_FFI *) 0 ;
  struct KeyID_FFI **result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct std_collections_Map_keys_crate_nested_KeyID_values_crate_nested_IdentityPublicKey_FFI **)&jarg1; 
  result = (struct KeyID_FFI **) ((arg1)->keys);
  *(struct KeyID_FFI ***)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_dash_sdk_exampleJNI_std_1collections_1Map_1keys_1crate_1nested_1KeyID_1values_1crate_1nested_1IdentityPublicKey_1FFI_1values_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct std_collections_Map_keys_crate_nested_KeyID_values_crate_nested_IdentityPublicKey_FFI *arg1 = (struct std_collections_Map_keys_crate_nested_KeyID_values_crate_nested_IdentityPublicKey_FFI *) 0 ;
  struct IdentityPublicKey_FFI **arg2 = (struct IdentityPublicKey_FFI **) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct std_collections_Map_keys_crate_nested_KeyID_values_crate_nested_IdentityPublicKey_FFI **)&jarg1; 
  arg2 = *(struct IdentityPublicKey_FFI ***)&jarg2; 
  if (arg1) (arg1)->values = arg2;
}


SWIGEXPORT jlong JNICALL Java_org_dash_sdk_exampleJNI_std_1collections_1Map_1keys_1crate_1nested_1KeyID_1values_1crate_1nested_1IdentityPublicKey_1FFI_1values_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct std_collections_Map_keys_crate_nested_KeyID_values_crate_nested_IdentityPublicKey_FFI *arg1 = (struct std_collections_Map_keys_crate_nested_KeyID_values_crate_nested_IdentityPublicKey_FFI *) 0 ;
  struct IdentityPublicKey_FFI **result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct std_collections_Map_keys_crate_nested_KeyID_values_crate_nested_IdentityPublicKey_FFI **)&jarg1; 
  result = (struct IdentityPublicKey_FFI **) ((arg1)->values);
  *(struct IdentityPublicKey_FFI ***)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_dash_sdk_exampleJNI_new_1std_1collections_1Map_1keys_1crate_1nested_1KeyID_1values_1crate_1nested_1IdentityPublicKey_1FFI(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct std_collections_Map_keys_crate_nested_KeyID_values_crate_nested_IdentityPublicKey_FFI *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct std_collections_Map_keys_crate_nested_KeyID_values_crate_nested_IdentityPublicKey_FFI *)calloc(1, sizeof(struct std_collections_Map_keys_crate_nested_KeyID_values_crate_nested_IdentityPublicKey_FFI));
  *(struct std_collections_Map_keys_crate_nested_KeyID_values_crate_nested_IdentityPublicKey_FFI **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_dash_sdk_exampleJNI_delete_1std_1collections_1Map_1keys_1crate_1nested_1KeyID_1values_1crate_1nested_1IdentityPublicKey_1FFI(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct std_collections_Map_keys_crate_nested_KeyID_values_crate_nested_IdentityPublicKey_FFI *arg1 = (struct std_collections_Map_keys_crate_nested_KeyID_values_crate_nested_IdentityPublicKey_FFI *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct std_collections_Map_keys_crate_nested_KeyID_values_crate_nested_IdentityPublicKey_FFI **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void JNICALL Java_org_dash_sdk_exampleJNI_Revision_1_10_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jobject jarg2) {
  struct Revision_FFI *arg1 = (struct Revision_FFI *) 0 ;
  uint64_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct Revision_FFI **)&jarg1; 
  {
    jclass clazz;
    jmethodID mid;
    jbyteArray ba;
    jbyte* bae;
    jsize sz;
    int i;
    
    if (!jarg2) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "BigInteger null");
      return ;
    }
    clazz = (*jenv)->GetObjectClass(jenv, jarg2);
    mid = (*jenv)->GetMethodID(jenv, clazz, "toByteArray", "()[B");
    ba = (jbyteArray)(*jenv)->CallObjectMethod(jenv, jarg2, mid);
    bae = (*jenv)->GetByteArrayElements(jenv, ba, 0);
    sz = (*jenv)->GetArrayLength(jenv, ba);
    arg2 = 0;
    if (sz > 0) {
      arg2 = (uint64_t)(signed char)bae[0];
      for(i=1; i<sz; i++) {
        arg2 = (arg2 << 8) | (uint64_t)(unsigned char)bae[i];
      }
    }
    (*jenv)->ReleaseByteArrayElements(jenv, ba, bae, 0);
  }
  if (arg1) (arg1)->_0 = arg2;
}


SWIGEXPORT jobject JNICALL Java_org_dash_sdk_exampleJNI_Revision_1_10_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jobject jresult = 0 ;
  struct Revision_FFI *arg1 = (struct Revision_FFI *) 0 ;
  uint64_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct Revision_FFI **)&jarg1; 
  result = (uint64_t) ((arg1)->_0);
  {
    jbyteArray ba = (*jenv)->NewByteArray(jenv, 9);
    jbyte* bae = (*jenv)->GetByteArrayElements(jenv, ba, 0);
    jclass clazz = (*jenv)->FindClass(jenv, "java/math/BigInteger");
    jmethodID mid = (*jenv)->GetMethodID(jenv, clazz, "<init>", "([B)V");
    jobject bigint;
    int i;
    
    bae[0] = 0;
    for(i=1; i<9; i++ ) {
      bae[i] = (jbyte)(result>>8*(8-i));
    }
    
    (*jenv)->ReleaseByteArrayElements(jenv, ba, bae, 0);
    bigint = (*jenv)->NewObject(jenv, clazz, mid, ba);
    (*jenv)->DeleteLocalRef(jenv, ba);
    jresult = bigint;
  }
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_dash_sdk_exampleJNI_new_1Revision(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct Revision_FFI *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct Revision_FFI *)calloc(1, sizeof(struct Revision_FFI));
  *(struct Revision_FFI **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_dash_sdk_exampleJNI_delete_1Revision(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct Revision_FFI *arg1 = (struct Revision_FFI *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct Revision_FFI **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void JNICALL Java_org_dash_sdk_exampleJNI_IdentityV0_1id_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  struct IdentityV0_FFI *arg1 = (struct IdentityV0_FFI *) 0 ;
  struct Identifier_FFI *arg2 = (struct Identifier_FFI *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(struct IdentityV0_FFI **)&jarg1; 
  arg2 = *(struct Identifier_FFI **)&jarg2; 
  if (arg1) (arg1)->id = arg2;
}


SWIGEXPORT jlong JNICALL Java_org_dash_sdk_exampleJNI_IdentityV0_1id_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct IdentityV0_FFI *arg1 = (struct IdentityV0_FFI *) 0 ;
  struct Identifier_FFI *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct IdentityV0_FFI **)&jarg1; 
  result = (struct Identifier_FFI *) ((arg1)->id);
  *(struct Identifier_FFI **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_dash_sdk_exampleJNI_IdentityV0_1public_1keys_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  struct IdentityV0_FFI *arg1 = (struct IdentityV0_FFI *) 0 ;
  struct std_collections_Map_keys_crate_nested_KeyID_values_crate_nested_IdentityPublicKey_FFI *arg2 = (struct std_collections_Map_keys_crate_nested_KeyID_values_crate_nested_IdentityPublicKey_FFI *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(struct IdentityV0_FFI **)&jarg1; 
  arg2 = *(struct std_collections_Map_keys_crate_nested_KeyID_values_crate_nested_IdentityPublicKey_FFI **)&jarg2; 
  if (arg1) (arg1)->public_keys = arg2;
}


SWIGEXPORT jlong JNICALL Java_org_dash_sdk_exampleJNI_IdentityV0_1public_1keys_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct IdentityV0_FFI *arg1 = (struct IdentityV0_FFI *) 0 ;
  struct std_collections_Map_keys_crate_nested_KeyID_values_crate_nested_IdentityPublicKey_FFI *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct IdentityV0_FFI **)&jarg1; 
  result = (struct std_collections_Map_keys_crate_nested_KeyID_values_crate_nested_IdentityPublicKey_FFI *) ((arg1)->public_keys);
  *(struct std_collections_Map_keys_crate_nested_KeyID_values_crate_nested_IdentityPublicKey_FFI **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_dash_sdk_exampleJNI_IdentityV0_1balance_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jobject jarg2) {
  struct IdentityV0_FFI *arg1 = (struct IdentityV0_FFI *) 0 ;
  uint64_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct IdentityV0_FFI **)&jarg1; 
  {
    jclass clazz;
    jmethodID mid;
    jbyteArray ba;
    jbyte* bae;
    jsize sz;
    int i;
    
    if (!jarg2) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "BigInteger null");
      return ;
    }
    clazz = (*jenv)->GetObjectClass(jenv, jarg2);
    mid = (*jenv)->GetMethodID(jenv, clazz, "toByteArray", "()[B");
    ba = (jbyteArray)(*jenv)->CallObjectMethod(jenv, jarg2, mid);
    bae = (*jenv)->GetByteArrayElements(jenv, ba, 0);
    sz = (*jenv)->GetArrayLength(jenv, ba);
    arg2 = 0;
    if (sz > 0) {
      arg2 = (uint64_t)(signed char)bae[0];
      for(i=1; i<sz; i++) {
        arg2 = (arg2 << 8) | (uint64_t)(unsigned char)bae[i];
      }
    }
    (*jenv)->ReleaseByteArrayElements(jenv, ba, bae, 0);
  }
  if (arg1) (arg1)->balance = arg2;
}


SWIGEXPORT jobject JNICALL Java_org_dash_sdk_exampleJNI_IdentityV0_1balance_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jobject jresult = 0 ;
  struct IdentityV0_FFI *arg1 = (struct IdentityV0_FFI *) 0 ;
  uint64_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct IdentityV0_FFI **)&jarg1; 
  result = (uint64_t) ((arg1)->balance);
  {
    jbyteArray ba = (*jenv)->NewByteArray(jenv, 9);
    jbyte* bae = (*jenv)->GetByteArrayElements(jenv, ba, 0);
    jclass clazz = (*jenv)->FindClass(jenv, "java/math/BigInteger");
    jmethodID mid = (*jenv)->GetMethodID(jenv, clazz, "<init>", "([B)V");
    jobject bigint;
    int i;
    
    bae[0] = 0;
    for(i=1; i<9; i++ ) {
      bae[i] = (jbyte)(result>>8*(8-i));
    }
    
    (*jenv)->ReleaseByteArrayElements(jenv, ba, bae, 0);
    bigint = (*jenv)->NewObject(jenv, clazz, mid, ba);
    (*jenv)->DeleteLocalRef(jenv, ba);
    jresult = bigint;
  }
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_dash_sdk_exampleJNI_IdentityV0_1revision_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  struct IdentityV0_FFI *arg1 = (struct IdentityV0_FFI *) 0 ;
  struct Revision_FFI *arg2 = (struct Revision_FFI *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(struct IdentityV0_FFI **)&jarg1; 
  arg2 = *(struct Revision_FFI **)&jarg2; 
  if (arg1) (arg1)->revision = arg2;
}


SWIGEXPORT jlong JNICALL Java_org_dash_sdk_exampleJNI_IdentityV0_1revision_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct IdentityV0_FFI *arg1 = (struct IdentityV0_FFI *) 0 ;
  struct Revision_FFI *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct IdentityV0_FFI **)&jarg1; 
  result = (struct Revision_FFI *) ((arg1)->revision);
  *(struct Revision_FFI **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_dash_sdk_exampleJNI_IdentityV0_1getPublicKey(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  jlong jresult = 0 ;
  struct IdentityV0_FFI *arg1 = (struct IdentityV0_FFI *) 0 ;
  uint32_t arg2 ;
  struct IdentityPublicKeyV0_FFI *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct IdentityV0_FFI **)&jarg1; 
  arg2 = (uint32_t)jarg2; 
  result = (struct IdentityPublicKeyV0_FFI *)IdentityV0_FFI_getPublicKey(arg1,arg2);
  *(struct IdentityPublicKeyV0_FFI **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_dash_sdk_exampleJNI_IdentityV0_1getPublicKeyById(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  jlong jresult = 0 ;
  struct IdentityV0_FFI *arg1 = (struct IdentityV0_FFI *) 0 ;
  uint32_t arg2 ;
  struct IdentityPublicKeyV0_FFI *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct IdentityV0_FFI **)&jarg1; 
  arg2 = (uint32_t)jarg2; 
  result = (struct IdentityPublicKeyV0_FFI *)IdentityV0_FFI_getPublicKeyById(arg1,arg2);
  *(struct IdentityPublicKeyV0_FFI **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_dash_sdk_exampleJNI_new_1IdentityV0(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct IdentityV0_FFI *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct IdentityV0_FFI *)calloc(1, sizeof(struct IdentityV0_FFI));
  *(struct IdentityV0_FFI **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_dash_sdk_exampleJNI_delete_1IdentityV0(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct IdentityV0_FFI *arg1 = (struct IdentityV0_FFI *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct IdentityV0_FFI **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void JNICALL Java_org_dash_sdk_exampleJNI_Identity_1tag_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct Identity_FFI *arg1 = (struct Identity_FFI *) 0 ;
  enum Identity_FFI_Tag arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct Identity_FFI **)&jarg1; 
  arg2 = (enum Identity_FFI_Tag)jarg2; 
  if (arg1) (arg1)->tag = arg2;
}


SWIGEXPORT jint JNICALL Java_org_dash_sdk_exampleJNI_Identity_1tag_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct Identity_FFI *arg1 = (struct Identity_FFI *) 0 ;
  enum Identity_FFI_Tag result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct Identity_FFI **)&jarg1; 
  result = (enum Identity_FFI_Tag) ((arg1)->tag);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_dash_sdk_exampleJNI_Identity_1v0_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  struct Identity_FFI *arg1 = (struct Identity_FFI *) 0 ;
  struct IdentityV0_FFI *arg2 = (struct IdentityV0_FFI *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(struct Identity_FFI **)&jarg1; 
  arg2 = *(struct IdentityV0_FFI **)&jarg2; 
  if (arg1) (arg1)->v0 = arg2;
}


SWIGEXPORT jlong JNICALL Java_org_dash_sdk_exampleJNI_Identity_1v0_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct Identity_FFI *arg1 = (struct Identity_FFI *) 0 ;
  struct IdentityV0_FFI *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct Identity_FFI **)&jarg1; 
  result = (struct IdentityV0_FFI *) ((arg1)->v0);
  *(struct IdentityV0_FFI **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_dash_sdk_exampleJNI_new_1Identity(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct Identity_FFI *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct Identity_FFI *)calloc(1, sizeof(struct Identity_FFI));
  *(struct Identity_FFI **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_dash_sdk_exampleJNI_delete_1Identity(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct Identity_FFI *arg1 = (struct Identity_FFI *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct Identity_FFI **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void JNICALL Java_org_dash_sdk_exampleJNI_HashID_1_10_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jbyteArray jarg2) {
  struct HashID_FFI *arg1 = (struct HashID_FFI *) 0 ;
  uint8_t (*arg2)[32] = (uint8_t (*)[32]) 0 ;
  uint8_t *byteArray2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct HashID_FFI **)&jarg1; 
  {
    //arg2 = (uint8_t (*)[32]) JCALL2(GetByteArrayElements, jenv, jarg2, 0);
    if (!jarg2) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null array");
      return ;
    }
    const jsize sz = (*jenv)->GetArrayLength(jenv, jarg2);
    jbyte* const jarr = (*jenv)->GetByteArrayElements(jenv, jarg2, 0);
    if (!jarr) return ;
    byteArray2 = calloc(1, 32); // this is a memory leak?
    memcpy(byteArray2, jarr, sz);
    (*jenv)->ReleaseByteArrayElements(jenv, jarg2, jarr, JNI_ABORT);
    arg2 = (uint8_t (*) [32])byteArray2;
  }
  if (arg1) (arg1)->_0 = (uint8_t (*)[32])arg2;
  {
    //JCALL3(ReleaseByteArrayElements, jenv, jarg2, (jbyte *) *arg2, 0);
  }
  
}


SWIGEXPORT jbyteArray JNICALL Java_org_dash_sdk_exampleJNI_HashID_1_10_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jbyteArray jresult = 0 ;
  struct HashID_FFI *arg1 = (struct HashID_FFI *) 0 ;
  uint8_t (*result)[32] = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct HashID_FFI **)&jarg1; 
  result = (uint8_t (*)[32]) ((arg1)->_0);
  {
    jresult = (*jenv)->NewByteArray(jenv, 32);
    (*jenv)->SetByteArrayRegion(jenv, jresult, 0, 32, (jbyte *)(*result));
  }
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_dash_sdk_exampleJNI_new_1HashID(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct HashID_FFI *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct HashID_FFI *)calloc(1, sizeof(struct HashID_FFI));
  *(struct HashID_FFI **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_dash_sdk_exampleJNI_delete_1HashID(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct HashID_FFI *arg1 = (struct HashID_FFI *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct HashID_FFI **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void JNICALL Java_org_dash_sdk_exampleJNI_std_1collections_1Map_1keys_1u32_1values_1crate_1nested_1HashID_1FFI_1count_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct std_collections_Map_keys_u32_values_crate_nested_HashID_FFI *arg1 = (struct std_collections_Map_keys_u32_values_crate_nested_HashID_FFI *) 0 ;
  uintptr_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct std_collections_Map_keys_u32_values_crate_nested_HashID_FFI **)&jarg1; 
  arg2 = (uintptr_t)jarg2; 
  if (arg1) (arg1)->count = arg2;
}


SWIGEXPORT jlong JNICALL Java_org_dash_sdk_exampleJNI_std_1collections_1Map_1keys_1u32_1values_1crate_1nested_1HashID_1FFI_1count_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct std_collections_Map_keys_u32_values_crate_nested_HashID_FFI *arg1 = (struct std_collections_Map_keys_u32_values_crate_nested_HashID_FFI *) 0 ;
  uintptr_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct std_collections_Map_keys_u32_values_crate_nested_HashID_FFI **)&jarg1; 
  result = (uintptr_t) ((arg1)->count);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_dash_sdk_exampleJNI_std_1collections_1Map_1keys_1u32_1values_1crate_1nested_1HashID_1FFI_1keys_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct std_collections_Map_keys_u32_values_crate_nested_HashID_FFI *arg1 = (struct std_collections_Map_keys_u32_values_crate_nested_HashID_FFI *) 0 ;
  uint32_t *arg2 = (uint32_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct std_collections_Map_keys_u32_values_crate_nested_HashID_FFI **)&jarg1; 
  arg2 = *(uint32_t **)&jarg2; 
  if (arg1) (arg1)->keys = arg2;
}


SWIGEXPORT jlong JNICALL Java_org_dash_sdk_exampleJNI_std_1collections_1Map_1keys_1u32_1values_1crate_1nested_1HashID_1FFI_1keys_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct std_collections_Map_keys_u32_values_crate_nested_HashID_FFI *arg1 = (struct std_collections_Map_keys_u32_values_crate_nested_HashID_FFI *) 0 ;
  uint32_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct std_collections_Map_keys_u32_values_crate_nested_HashID_FFI **)&jarg1; 
  result = (uint32_t *) ((arg1)->keys);
  *(uint32_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_dash_sdk_exampleJNI_std_1collections_1Map_1keys_1u32_1values_1crate_1nested_1HashID_1FFI_1values_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct std_collections_Map_keys_u32_values_crate_nested_HashID_FFI *arg1 = (struct std_collections_Map_keys_u32_values_crate_nested_HashID_FFI *) 0 ;
  struct HashID_FFI **arg2 = (struct HashID_FFI **) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct std_collections_Map_keys_u32_values_crate_nested_HashID_FFI **)&jarg1; 
  arg2 = *(struct HashID_FFI ***)&jarg2; 
  if (arg1) (arg1)->values = arg2;
}


SWIGEXPORT jlong JNICALL Java_org_dash_sdk_exampleJNI_std_1collections_1Map_1keys_1u32_1values_1crate_1nested_1HashID_1FFI_1values_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct std_collections_Map_keys_u32_values_crate_nested_HashID_FFI *arg1 = (struct std_collections_Map_keys_u32_values_crate_nested_HashID_FFI *) 0 ;
  struct HashID_FFI **result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct std_collections_Map_keys_u32_values_crate_nested_HashID_FFI **)&jarg1; 
  result = (struct HashID_FFI **) ((arg1)->values);
  *(struct HashID_FFI ***)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_dash_sdk_exampleJNI_new_1std_1collections_1Map_1keys_1u32_1values_1crate_1nested_1HashID_1FFI(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct std_collections_Map_keys_u32_values_crate_nested_HashID_FFI *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct std_collections_Map_keys_u32_values_crate_nested_HashID_FFI *)calloc(1, sizeof(struct std_collections_Map_keys_u32_values_crate_nested_HashID_FFI));
  *(struct std_collections_Map_keys_u32_values_crate_nested_HashID_FFI **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_dash_sdk_exampleJNI_delete_1std_1collections_1Map_1keys_1u32_1values_1crate_1nested_1HashID_1FFI(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct std_collections_Map_keys_u32_values_crate_nested_HashID_FFI *arg1 = (struct std_collections_Map_keys_u32_values_crate_nested_HashID_FFI *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct std_collections_Map_keys_u32_values_crate_nested_HashID_FFI **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void JNICALL Java_org_dash_sdk_exampleJNI_std_1collections_1Map_1keys_1crate_1chain_1common_1chain_1type_1ChainType_1values_1crate_1nested_1HashID_1FFI_1count_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct std_collections_Map_keys_crate_chain_common_chain_type_ChainType_values_crate_nested_HashID_FFI *arg1 = (struct std_collections_Map_keys_crate_chain_common_chain_type_ChainType_values_crate_nested_HashID_FFI *) 0 ;
  uintptr_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct std_collections_Map_keys_crate_chain_common_chain_type_ChainType_values_crate_nested_HashID_FFI **)&jarg1; 
  arg2 = (uintptr_t)jarg2; 
  if (arg1) (arg1)->count = arg2;
}


SWIGEXPORT jlong JNICALL Java_org_dash_sdk_exampleJNI_std_1collections_1Map_1keys_1crate_1chain_1common_1chain_1type_1ChainType_1values_1crate_1nested_1HashID_1FFI_1count_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct std_collections_Map_keys_crate_chain_common_chain_type_ChainType_values_crate_nested_HashID_FFI *arg1 = (struct std_collections_Map_keys_crate_chain_common_chain_type_ChainType_values_crate_nested_HashID_FFI *) 0 ;
  uintptr_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct std_collections_Map_keys_crate_chain_common_chain_type_ChainType_values_crate_nested_HashID_FFI **)&jarg1; 
  result = (uintptr_t) ((arg1)->count);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_dash_sdk_exampleJNI_std_1collections_1Map_1keys_1crate_1chain_1common_1chain_1type_1ChainType_1values_1crate_1nested_1HashID_1FFI_1keys_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct std_collections_Map_keys_crate_chain_common_chain_type_ChainType_values_crate_nested_HashID_FFI *arg1 = (struct std_collections_Map_keys_crate_chain_common_chain_type_ChainType_values_crate_nested_HashID_FFI *) 0 ;
  enum ChainType_FFI **arg2 = (enum ChainType_FFI **) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct std_collections_Map_keys_crate_chain_common_chain_type_ChainType_values_crate_nested_HashID_FFI **)&jarg1; 
  arg2 = *(enum ChainType_FFI ***)&jarg2; 
  if (arg1) (arg1)->keys = arg2;
}


SWIGEXPORT jlong JNICALL Java_org_dash_sdk_exampleJNI_std_1collections_1Map_1keys_1crate_1chain_1common_1chain_1type_1ChainType_1values_1crate_1nested_1HashID_1FFI_1keys_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct std_collections_Map_keys_crate_chain_common_chain_type_ChainType_values_crate_nested_HashID_FFI *arg1 = (struct std_collections_Map_keys_crate_chain_common_chain_type_ChainType_values_crate_nested_HashID_FFI *) 0 ;
  enum ChainType_FFI **result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct std_collections_Map_keys_crate_chain_common_chain_type_ChainType_values_crate_nested_HashID_FFI **)&jarg1; 
  result = (enum ChainType_FFI **) ((arg1)->keys);
  *(enum ChainType_FFI ***)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_dash_sdk_exampleJNI_std_1collections_1Map_1keys_1crate_1chain_1common_1chain_1type_1ChainType_1values_1crate_1nested_1HashID_1FFI_1values_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct std_collections_Map_keys_crate_chain_common_chain_type_ChainType_values_crate_nested_HashID_FFI *arg1 = (struct std_collections_Map_keys_crate_chain_common_chain_type_ChainType_values_crate_nested_HashID_FFI *) 0 ;
  struct HashID_FFI **arg2 = (struct HashID_FFI **) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct std_collections_Map_keys_crate_chain_common_chain_type_ChainType_values_crate_nested_HashID_FFI **)&jarg1; 
  arg2 = *(struct HashID_FFI ***)&jarg2; 
  if (arg1) (arg1)->values = arg2;
}


SWIGEXPORT jlong JNICALL Java_org_dash_sdk_exampleJNI_std_1collections_1Map_1keys_1crate_1chain_1common_1chain_1type_1ChainType_1values_1crate_1nested_1HashID_1FFI_1values_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct std_collections_Map_keys_crate_chain_common_chain_type_ChainType_values_crate_nested_HashID_FFI *arg1 = (struct std_collections_Map_keys_crate_chain_common_chain_type_ChainType_values_crate_nested_HashID_FFI *) 0 ;
  struct HashID_FFI **result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct std_collections_Map_keys_crate_chain_common_chain_type_ChainType_values_crate_nested_HashID_FFI **)&jarg1; 
  result = (struct HashID_FFI **) ((arg1)->values);
  *(struct HashID_FFI ***)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_dash_sdk_exampleJNI_new_1std_1collections_1Map_1keys_1crate_1chain_1common_1chain_1type_1ChainType_1values_1crate_1nested_1HashID_1FFI(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct std_collections_Map_keys_crate_chain_common_chain_type_ChainType_values_crate_nested_HashID_FFI *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct std_collections_Map_keys_crate_chain_common_chain_type_ChainType_values_crate_nested_HashID_FFI *)calloc(1, sizeof(struct std_collections_Map_keys_crate_chain_common_chain_type_ChainType_values_crate_nested_HashID_FFI));
  *(struct std_collections_Map_keys_crate_chain_common_chain_type_ChainType_values_crate_nested_HashID_FFI **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_dash_sdk_exampleJNI_delete_1std_1collections_1Map_1keys_1crate_1chain_1common_1chain_1type_1ChainType_1values_1crate_1nested_1HashID_1FFI(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct std_collections_Map_keys_crate_chain_common_chain_type_ChainType_values_crate_nested_HashID_FFI *arg1 = (struct std_collections_Map_keys_crate_chain_common_chain_type_ChainType_values_crate_nested_HashID_FFI *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct std_collections_Map_keys_crate_chain_common_chain_type_ChainType_values_crate_nested_HashID_FFI **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT jlong JNICALL Java_org_dash_sdk_exampleJNI_ffiGetAnIdentity(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct Identity_FFI *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct Identity_FFI *)ffi_get_an_identity();
  *(struct Identity_FFI **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_dash_sdk_exampleJNI_ffiFindHashByU32(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jobject jarg2_) {
  jlong jresult = 0 ;
  uint32_t arg1 ;
  struct std_collections_Map_keys_u32_values_crate_nested_HashID_FFI *arg2 = (struct std_collections_Map_keys_u32_values_crate_nested_HashID_FFI *) 0 ;
  struct HashID_FFI *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg2_;
  arg1 = (uint32_t)jarg1; 
  arg2 = *(struct std_collections_Map_keys_u32_values_crate_nested_HashID_FFI **)&jarg2; 
  result = (struct HashID_FFI *)ffi_find_hash_by_u32(arg1,arg2);
  *(struct HashID_FFI **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_dash_sdk_exampleJNI_ffiGetIdentity(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct Identifier_FFI *arg1 = (struct Identifier_FFI *) 0 ;
  struct Identity_FFI *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct Identifier_FFI **)&jarg1; 
  result = (struct Identity_FFI *)ffi_get_identity(arg1);
  *(struct Identity_FFI **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_org_dash_sdk_exampleJNI_ffiGetChainHashesByMap(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  struct std_collections_Map_keys_crate_chain_common_chain_type_ChainType_values_crate_nested_HashID_FFI *arg1 = (struct std_collections_Map_keys_crate_chain_common_chain_type_ChainType_values_crate_nested_HashID_FFI *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct std_collections_Map_keys_crate_chain_common_chain_type_ChainType_values_crate_nested_HashID_FFI **)&jarg1; 
  result = (char *)ffi_get_chain_hashes_by_map(arg1);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_org_dash_sdk_exampleJNI_ffiAddressWithScriptPubkey(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  struct Vec_u8_FFI *arg1 = (struct Vec_u8_FFI *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct Vec_u8_FFI **)&jarg1; 
  result = (char *)ffi_address_with_script_pubkey(arg1);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_org_dash_sdk_exampleJNI_ffiGetChainTypeString(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jstring jresult = 0 ;
  enum ChainType_FFI *arg1 = (enum ChainType_FFI *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(enum ChainType_FFI **)&jarg1; 
  result = (char *)ffi_get_chain_type_string(arg1);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


#ifdef __cplusplus
}
#endif

