%ignore purpose_AUTHENTICATION_ctor();
%rename(Purpose) ferment_example_identity_identity_Purpose;
%rename(KeyType) ferment_example_identity_identity_KeyType;
%rename(SecurityLevel) ferment_example_identity_identity_SecurityLevel;

%rename(MEDIUM) ferment_example_identity_identity_SecurityLevel_MEDIUM;
%rename(MASTER) ferment_example_identity_identity_SecurityLevel_MASTER;
%rename(CRITICAL) ferment_example_identity_identity_SecurityLevel_CRITICAL;
%rename(HIGH) ferment_example_identity_identity_SecurityLevel_HIGH;

%rename(AUTHENTICATION) ferment_example_identity_identity_Purpose_AUTHENTICATION;
%rename(ENCRYPTION) ferment_example_identity_identity_Purpose_ENCRYPTION;
%rename(DECRYPTION) ferment_example_identity_identity_Purpose_DECRYPTION;
%rename(WITHDRAW) ferment_example_identity_identity_Purpose_WITHDRAW;
%rename(SYSTEM) ferment_example_identity_identity_Purpose_SYSTEM;
%rename(VOTING) ferment_example_identity_identity_Purpose_VOTING;

%rename (ECDSA_SECP256K1) ferment_example_identity_identity_KeyType_ECDSA_SECP256K1;
%rename (BLS12_381) ferment_example_identity_identity_KeyType_BLS12_381;
%rename (ECDSA_HASH160) ferment_example_identity_identity_KeyType_ECDSA_HASH160;
%rename (BIP13_SCRIPT_HASH) ferment_example_identity_identity_KeyType_BIP13_SCRIPT_HASH;
%rename (EDDSA_25519_HASH160) ferment_example_identity_identity_KeyType_EDDSA_25519_HASH160;