/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dash.sdk;

import org.dash.sdk.base.BaseObject;

public class crate_nested_ProtocolError_MaxEncodedBytesReachedError_Body extends BaseObject {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected crate_nested_ProtocolError_MaxEncodedBytesReachedError_Body(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(crate_nested_ProtocolError_MaxEncodedBytesReachedError_Body obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        exampleJNI.delete_crate_nested_ProtocolError_MaxEncodedBytesReachedError_Body(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected long getCPointer() {
    return swigCPtr;
  }

  public void setMax_size_kbytes(long value) {
    exampleJNI.crate_nested_ProtocolError_MaxEncodedBytesReachedError_Body_max_size_kbytes_set(swigCPtr, this, value);
  }

  public long getMax_size_kbytes() {
    return exampleJNI.crate_nested_ProtocolError_MaxEncodedBytesReachedError_Body_max_size_kbytes_get(swigCPtr, this);
  }

  public void setSize_hit(long value) {
    exampleJNI.crate_nested_ProtocolError_MaxEncodedBytesReachedError_Body_size_hit_set(swigCPtr, this, value);
  }

  public long getSize_hit() {
    return exampleJNI.crate_nested_ProtocolError_MaxEncodedBytesReachedError_Body_size_hit_get(swigCPtr, this);
  }

}
