/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dash.sdk;

import org.dash.sdk.base.BaseObject;

public class crate_nested_ProtocolError_UnknownVersionMismatch_Body extends BaseObject {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected crate_nested_ProtocolError_UnknownVersionMismatch_Body(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(crate_nested_ProtocolError_UnknownVersionMismatch_Body obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        exampleJNI.delete_crate_nested_ProtocolError_UnknownVersionMismatch_Body(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected long getCPointer() {
    return swigCPtr;
  }

  public void setMethod(String value) {
    exampleJNI.crate_nested_ProtocolError_UnknownVersionMismatch_Body_method_set(swigCPtr, this, value);
  }

  public String getMethod() {
    return exampleJNI.crate_nested_ProtocolError_UnknownVersionMismatch_Body_method_get(swigCPtr, this);
  }

  public void setKnown_versions(SWIGTYPE_p_Vec_crate_nested_FeatureVersion value) {
    exampleJNI.crate_nested_ProtocolError_UnknownVersionMismatch_Body_known_versions_set(swigCPtr, this, SWIGTYPE_p_Vec_crate_nested_FeatureVersion.getCPtr(value));
  }

  public SWIGTYPE_p_Vec_crate_nested_FeatureVersion getKnown_versions() {
    long cPtr = exampleJNI.crate_nested_ProtocolError_UnknownVersionMismatch_Body_known_versions_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_Vec_crate_nested_FeatureVersion(cPtr, false);
  }

  public void setReceived(crate_nested_FeatureVersion value) {
    exampleJNI.crate_nested_ProtocolError_UnknownVersionMismatch_Body_received_set(swigCPtr, this, crate_nested_FeatureVersion.getCPtr(value), value);
  }

  public crate_nested_FeatureVersion getReceived() {
    long cPtr = exampleJNI.crate_nested_ProtocolError_UnknownVersionMismatch_Body_received_get(swigCPtr, this);
    return (cPtr == 0) ? null : new crate_nested_FeatureVersion(cPtr, false);
  }

}
