/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dash.sdk;

import org.dash.sdk.base.BaseObject;

public class crate_nested_HashID extends BaseObject {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected crate_nested_HashID(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(crate_nested_HashID obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        exampleJNI.delete_crate_nested_HashID(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected long getCPointer() {
    return swigCPtr;
  }

  public void set_0(byte[] value) {
    exampleJNI.crate_nested_HashID__0_set(swigCPtr, this, value);
  }

  public byte[] get_0() {
    return exampleJNI.crate_nested_HashID__0_get(swigCPtr, this);
  }

}
