/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dash.sdk;

import org.dash.sdk.base.BaseObject;

public class crate_nested_FeatureVersionBounds extends BaseObject {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected crate_nested_FeatureVersionBounds(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(crate_nested_FeatureVersionBounds obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        exampleJNI.delete_crate_nested_FeatureVersionBounds(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected long getCPointer() {
    return swigCPtr;
  }

  public void setMin_version(crate_nested_FeatureVersion value) {
    exampleJNI.crate_nested_FeatureVersionBounds_min_version_set(swigCPtr, this, crate_nested_FeatureVersion.getCPtr(value), value);
  }

  public crate_nested_FeatureVersion getMin_version() {
    long cPtr = exampleJNI.crate_nested_FeatureVersionBounds_min_version_get(swigCPtr, this);
    return (cPtr == 0) ? null : new crate_nested_FeatureVersion(cPtr, false);
  }

  public void setMax_version(crate_nested_FeatureVersion value) {
    exampleJNI.crate_nested_FeatureVersionBounds_max_version_set(swigCPtr, this, crate_nested_FeatureVersion.getCPtr(value), value);
  }

  public crate_nested_FeatureVersion getMax_version() {
    long cPtr = exampleJNI.crate_nested_FeatureVersionBounds_max_version_get(swigCPtr, this);
    return (cPtr == 0) ? null : new crate_nested_FeatureVersion(cPtr, false);
  }

  public void setDefault_current_version(crate_nested_FeatureVersion value) {
    exampleJNI.crate_nested_FeatureVersionBounds_default_current_version_set(swigCPtr, this, crate_nested_FeatureVersion.getCPtr(value), value);
  }

  public crate_nested_FeatureVersion getDefault_current_version() {
    long cPtr = exampleJNI.crate_nested_FeatureVersionBounds_default_current_version_get(swigCPtr, this);
    return (cPtr == 0) ? null : new crate_nested_FeatureVersion(cPtr, false);
  }

}
