/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dash.sdk;

import org.dash.sdk.base.BaseObject;

public class crate_nested_ProtocolError extends BaseObject {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected crate_nested_ProtocolError(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(crate_nested_ProtocolError obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        exampleJNI.delete_crate_nested_ProtocolError(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected long getCPointer() {
    return swigCPtr;
  }

  public void setTag(crate_nested_ProtocolError_Tag value) {
    exampleJNI.crate_nested_ProtocolError_tag_set(swigCPtr, this, value.swigValue());
  }

  public crate_nested_ProtocolError_Tag getTag() {
    return crate_nested_ProtocolError_Tag.swigToEnum(exampleJNI.crate_nested_ProtocolError_tag_get(swigCPtr, this));
  }

  public void setIdentifier_error(String value) {
    exampleJNI.crate_nested_ProtocolError_identifier_error_set(swigCPtr, this, value);
  }

  public String getIdentifier_error() {
    return exampleJNI.crate_nested_ProtocolError_identifier_error_get(swigCPtr, this);
  }

  public void setString_decode_error(String value) {
    exampleJNI.crate_nested_ProtocolError_string_decode_error_set(swigCPtr, this, value);
  }

  public String getString_decode_error() {
    return exampleJNI.crate_nested_ProtocolError_string_decode_error_get(swigCPtr, this);
  }

  public void setString_decode_error2(crate_nested_ProtocolError_StringDecodeError2_Body value) {
    exampleJNI.crate_nested_ProtocolError_string_decode_error2_set(swigCPtr, this, crate_nested_ProtocolError_StringDecodeError2_Body.getCPtr(value), value);
  }

  public crate_nested_ProtocolError_StringDecodeError2_Body getString_decode_error2() {
    long cPtr = exampleJNI.crate_nested_ProtocolError_string_decode_error2_get(swigCPtr, this);
    return (cPtr == 0) ? null : new crate_nested_ProtocolError_StringDecodeError2_Body(cPtr, false);
  }

  public void setMax_encoded_bytes_reached_error(crate_nested_ProtocolError_MaxEncodedBytesReachedError_Body value) {
    exampleJNI.crate_nested_ProtocolError_max_encoded_bytes_reached_error_set(swigCPtr, this, crate_nested_ProtocolError_MaxEncodedBytesReachedError_Body.getCPtr(value), value);
  }

  public crate_nested_ProtocolError_MaxEncodedBytesReachedError_Body getMax_encoded_bytes_reached_error() {
    long cPtr = exampleJNI.crate_nested_ProtocolError_max_encoded_bytes_reached_error_get(swigCPtr, this);
    return (cPtr == 0) ? null : new crate_nested_ProtocolError_MaxEncodedBytesReachedError_Body(cPtr, false);
  }

  public void setEncoding_error(String value) {
    exampleJNI.crate_nested_ProtocolError_encoding_error_set(swigCPtr, this, value);
  }

  public String getEncoding_error() {
    return exampleJNI.crate_nested_ProtocolError_encoding_error_get(swigCPtr, this);
  }

  public void setEncoding_error2(String value) {
    exampleJNI.crate_nested_ProtocolError_encoding_error2_set(swigCPtr, this, value);
  }

  public String getEncoding_error2() {
    return exampleJNI.crate_nested_ProtocolError_encoding_error2_get(swigCPtr, this);
  }

  public void setData_contract_not_present_error(crate_nested_DataContractNotPresentError value) {
    exampleJNI.crate_nested_ProtocolError_data_contract_not_present_error_set(swigCPtr, this, crate_nested_DataContractNotPresentError.getCPtr(value), value);
  }

  public crate_nested_DataContractNotPresentError getData_contract_not_present_error() {
    long cPtr = exampleJNI.crate_nested_ProtocolError_data_contract_not_present_error_get(swigCPtr, this);
    return (cPtr == 0) ? null : new crate_nested_DataContractNotPresentError(cPtr, false);
  }

  public void setUnknown_version_mismatch(crate_nested_ProtocolError_UnknownVersionMismatch_Body value) {
    exampleJNI.crate_nested_ProtocolError_unknown_version_mismatch_set(swigCPtr, this, crate_nested_ProtocolError_UnknownVersionMismatch_Body.getCPtr(value), value);
  }

  public crate_nested_ProtocolError_UnknownVersionMismatch_Body getUnknown_version_mismatch() {
    long cPtr = exampleJNI.crate_nested_ProtocolError_unknown_version_mismatch_get(swigCPtr, this);
    return (cPtr == 0) ? null : new crate_nested_ProtocolError_UnknownVersionMismatch_Body(cPtr, false);
  }

}
