/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dash.sdk;

import org.dash.sdk.base.BaseObject;

public class crate_nested_PlatformVersion extends BaseObject {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected crate_nested_PlatformVersion(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(crate_nested_PlatformVersion obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        exampleJNI.delete_crate_nested_PlatformVersion(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected long getCPointer() {
    return swigCPtr;
  }

  public void setProtocol_version(long value) {
    exampleJNI.crate_nested_PlatformVersion_protocol_version_set(swigCPtr, this, value);
  }

  public long getProtocol_version() {
    return exampleJNI.crate_nested_PlatformVersion_protocol_version_get(swigCPtr, this);
  }

  public void setIdentity(crate_nested_FeatureVersionBounds value) {
    exampleJNI.crate_nested_PlatformVersion_identity_set(swigCPtr, this, crate_nested_FeatureVersionBounds.getCPtr(value), value);
  }

  public crate_nested_FeatureVersionBounds getIdentity() {
    long cPtr = exampleJNI.crate_nested_PlatformVersion_identity_get(swigCPtr, this);
    return (cPtr == 0) ? null : new crate_nested_FeatureVersionBounds(cPtr, false);
  }

  public void setProofs(crate_nested_FeatureVersionBounds value) {
    exampleJNI.crate_nested_PlatformVersion_proofs_set(swigCPtr, this, crate_nested_FeatureVersionBounds.getCPtr(value), value);
  }

  public crate_nested_FeatureVersionBounds getProofs() {
    long cPtr = exampleJNI.crate_nested_PlatformVersion_proofs_get(swigCPtr, this);
    return (cPtr == 0) ? null : new crate_nested_FeatureVersionBounds(cPtr, false);
  }

}
