/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dash.sdk;

public class example {
  public static RootStruct rootStructCtor(String name) {
    long cPtr = exampleJNI.rootStructCtor(name);
    return (cPtr == 0) ? null : new RootStruct(cPtr, false);
  }

  public static void rootStructDestroy(RootStruct ffi) {
    exampleJNI.rootStructDestroy(RootStruct.getCPtr(ffi), ffi);
  }

  public static VecU8Holder vecU8HolderCtor(byte[] first) {
    long cPtr = exampleJNI.vecU8HolderCtor(first);
    return (cPtr == 0) ? null : new VecU8Holder(cPtr, false);
  }

  public static void vecU8HolderDestroy(VecU8Holder ffi) {
    exampleJNI.vecU8HolderDestroy(VecU8Holder.getCPtr(ffi), ffi);
  }

  public static OuterStruct createOuter(InnerStruct is1, InnerStruct is2) {
    long cPtr = exampleJNI.createOuter(InnerStruct.getCPtr(is1), is1, InnerStruct.getCPtr(is2), is2);
    return (cPtr == 0) ? null : new OuterStruct(cPtr, false);
  }

  public static InnerStruct innerStructCtor(java.math.BigInteger first, java.math.BigInteger second) {
    long cPtr = exampleJNI.innerStructCtor(first, second);
    return (cPtr == 0) ? null : new InnerStruct(cPtr, false);
  }

  public static void innerStructDestroy(InnerStruct ffi) {
    exampleJNI.innerStructDestroy(InnerStruct.getCPtr(ffi), ffi);
  }

  public static OuterStruct outerStructCtor(InnerStruct first, InnerStruct second) {
    long cPtr = exampleJNI.outerStructCtor(InnerStruct.getCPtr(first), first, InnerStruct.getCPtr(second), second);
    return (cPtr == 0) ? null : new OuterStruct(cPtr, false);
  }

  public static void outerStructDestroy(OuterStruct ffi) {
    exampleJNI.outerStructDestroy(OuterStruct.getCPtr(ffi), ffi);
  }

  public static BinaryData binaryDataCtor(byte[] o_0) {
    long cPtr = exampleJNI.binaryDataCtor(o_0);
    return (cPtr == 0) ? null : new BinaryData(cPtr, false);
  }

  public static void binaryDataDestroy(BinaryData ffi) {
    exampleJNI.binaryDataDestroy(BinaryData.getCPtr(ffi), ffi);
  }

  public static OptionalFeatureVersion optionalFeatureVersionCtor(int o_0) {
    long cPtr = exampleJNI.optionalFeatureVersionCtor(o_0);
    return (cPtr == 0) ? null : new OptionalFeatureVersion(cPtr, false);
  }

  public static void optionalFeatureVersionDestroy(OptionalFeatureVersion ffi) {
    exampleJNI.optionalFeatureVersionDestroy(OptionalFeatureVersion.getCPtr(ffi), ffi);
  }

  public static Identifier identifierCtor(IdentifierBytes32 o_0) {
    long cPtr = exampleJNI.identifierCtor(IdentifierBytes32.getCPtr(o_0), o_0);
    return (cPtr == 0) ? null : new Identifier(cPtr, false);
  }

  public static void identifierDestroy(Identifier ffi) {
    exampleJNI.identifierDestroy(Identifier.getCPtr(ffi), ffi);
  }

  public static FeatureVersionBounds featureVersionBoundsCtor(SWIGTYPE_p_FeatureVersion min_version, SWIGTYPE_p_FeatureVersion max_version, SWIGTYPE_p_FeatureVersion default_current_version) {
    long cPtr = exampleJNI.featureVersionBoundsCtor(SWIGTYPE_p_FeatureVersion.getCPtr(min_version), SWIGTYPE_p_FeatureVersion.getCPtr(max_version), SWIGTYPE_p_FeatureVersion.getCPtr(default_current_version));
    return (cPtr == 0) ? null : new FeatureVersionBounds(cPtr, false);
  }

  public static void featureVersionBoundsDestroy(FeatureVersionBounds ffi) {
    exampleJNI.featureVersionBoundsDestroy(FeatureVersionBounds.getCPtr(ffi), ffi);
  }

  public static ProtocolError protocolErrorIdentifierErrorCtor(String o_0) {
    long cPtr = exampleJNI.protocolErrorIdentifierErrorCtor(o_0);
    return (cPtr == 0) ? null : new ProtocolError(cPtr, false);
  }

  public static ProtocolError protocolErrorStringDecodeErrorCtor(String o_0) {
    long cPtr = exampleJNI.protocolErrorStringDecodeErrorCtor(o_0);
    return (cPtr == 0) ? null : new ProtocolError(cPtr, false);
  }

  public static ProtocolError protocolErrorStringDecodeError2Ctor(String o_0, long o_1) {
    long cPtr = exampleJNI.protocolErrorStringDecodeError2Ctor(o_0, o_1);
    return (cPtr == 0) ? null : new ProtocolError(cPtr, false);
  }

  public static ProtocolError protocolErrorEmptyPublicKeyDataErrorCtor() {
    long cPtr = exampleJNI.protocolErrorEmptyPublicKeyDataErrorCtor();
    return (cPtr == 0) ? null : new ProtocolError(cPtr, false);
  }

  public static ProtocolError protocolErrorMaxEncodedBytesReachedErrorCtor(long max_size_kbytes, long size_hit) {
    long cPtr = exampleJNI.protocolErrorMaxEncodedBytesReachedErrorCtor(max_size_kbytes, size_hit);
    return (cPtr == 0) ? null : new ProtocolError(cPtr, false);
  }

  public static ProtocolError protocolErrorEncodingErrorCtor(String o_0) {
    long cPtr = exampleJNI.protocolErrorEncodingErrorCtor(o_0);
    return (cPtr == 0) ? null : new ProtocolError(cPtr, false);
  }

  public static ProtocolError protocolErrorEncodingError2Ctor(String o_0) {
    long cPtr = exampleJNI.protocolErrorEncodingError2Ctor(o_0);
    return (cPtr == 0) ? null : new ProtocolError(cPtr, false);
  }

  public static ProtocolError protocolErrorDataContractNotPresentErrorCtor(DataContractNotPresentError o_0) {
    long cPtr = exampleJNI.protocolErrorDataContractNotPresentErrorCtor(DataContractNotPresentError.getCPtr(o_0), o_0);
    return (cPtr == 0) ? null : new ProtocolError(cPtr, false);
  }

  public static ProtocolError protocolErrorUnknownVersionMismatchCtor(String method, SWIGTYPE_p_Vec_crate_nested_FeatureVersion known_versions, SWIGTYPE_p_FeatureVersion received) {
    long cPtr = exampleJNI.protocolErrorUnknownVersionMismatchCtor(method, SWIGTYPE_p_Vec_crate_nested_FeatureVersion.getCPtr(known_versions), SWIGTYPE_p_FeatureVersion.getCPtr(received));
    return (cPtr == 0) ? null : new ProtocolError(cPtr, false);
  }

  public static void protocolErrorDestroy(ProtocolError ffi) {
    exampleJNI.protocolErrorDestroy(ProtocolError.getCPtr(ffi), ffi);
  }

  public static IdentifierBytes32 identifierBytes32Ctor(byte[] o_0) {
    long cPtr = exampleJNI.identifierBytes32Ctor(o_0);
    return (cPtr == 0) ? null : new IdentifierBytes32(cPtr, false);
  }

  public static void identifierBytes32Destroy(IdentifierBytes32 ffi) {
    exampleJNI.identifierBytes32Destroy(IdentifierBytes32.getCPtr(ffi), ffi);
  }

  public static SWIGTYPE_p_FeatureVersion featureVersionCtor(int o_0) {
    long cPtr = exampleJNI.featureVersionCtor(o_0);
    return (cPtr == 0) ? null : new SWIGTYPE_p_FeatureVersion(cPtr, false);
  }

  public static void featureVersionDestroy(SWIGTYPE_p_FeatureVersion ffi) {
    exampleJNI.featureVersionDestroy(SWIGTYPE_p_FeatureVersion.getCPtr(ffi));
  }

  public static PlatformVersion platformVersionCtor(long protocol_version, FeatureVersionBounds identity, FeatureVersionBounds proofs) {
    long cPtr = exampleJNI.platformVersionCtor(protocol_version, FeatureVersionBounds.getCPtr(identity), identity, FeatureVersionBounds.getCPtr(proofs), proofs);
    return (cPtr == 0) ? null : new PlatformVersion(cPtr, false);
  }

  public static void platformVersionDestroy(PlatformVersion ffi) {
    exampleJNI.platformVersionDestroy(PlatformVersion.getCPtr(ffi), ffi);
  }

  public static DataContractNotPresentError dataContractNotPresentErrorCtor(Identifier data_contract_id) {
    long cPtr = exampleJNI.dataContractNotPresentErrorCtor(Identifier.getCPtr(data_contract_id), data_contract_id);
    return (cPtr == 0) ? null : new DataContractNotPresentError(cPtr, false);
  }

  public static void dataContractNotPresentErrorDestroy(DataContractNotPresentError ffi) {
    exampleJNI.dataContractNotPresentErrorDestroy(DataContractNotPresentError.getCPtr(ffi), ffi);
  }

  public static Revision revisionCtor(java.math.BigInteger o_0) {
    long cPtr = exampleJNI.revisionCtor(o_0);
    return (cPtr == 0) ? null : new Revision(cPtr, false);
  }

  public static void revisionDestroy(Revision ffi) {
    exampleJNI.revisionDestroy(Revision.getCPtr(ffi), ffi);
  }

  public static void identityPublicKeyV0Destroy(IdentityPublicKeyV0 ffi) {
    exampleJNI.identityPublicKeyV0Destroy(IdentityPublicKeyV0.getCPtr(ffi), ffi);
  }

  public static Identity identityV0Ctor(IdentityV0 o_0) {
    long cPtr = exampleJNI.identityV0Ctor__SWIG_0(IdentityV0.getCPtr(o_0), o_0);
    return (cPtr == 0) ? null : new Identity(cPtr, false);
  }

  public static void identityDestroy(Identity ffi) {
    exampleJNI.identityDestroy(Identity.getCPtr(ffi), ffi);
  }

  public static IdentityV0 identityV0Ctor(Identifier id, std_collections_Map_keys_crate_identity_identity_KeyID_values_crate_identity_identity_IdentityPublicKey public_keys, java.math.BigInteger balance, Revision revision) {
    long cPtr = exampleJNI.identityV0Ctor__SWIG_1(Identifier.getCPtr(id), id, std_collections_Map_keys_crate_identity_identity_KeyID_values_crate_identity_identity_IdentityPublicKey.getCPtr(public_keys), public_keys, balance, Revision.getCPtr(revision), revision);
    return (cPtr == 0) ? null : new IdentityV0(cPtr, false);
  }

  public static void identityV0Destroy(IdentityV0 ffi) {
    exampleJNI.identityV0Destroy(IdentityV0.getCPtr(ffi), ffi);
  }

  public static Identity getAnIdentity() {
    long cPtr = exampleJNI.getAnIdentity();
    return (cPtr == 0) ? null : new Identity(cPtr, true);
  }

  public static IdentityPublicKeyV0 randomKey(KeyID id) {
    long cPtr = exampleJNI.randomKey(KeyID.getCPtr(id), id);
    return (cPtr == 0) ? null : new IdentityPublicKeyV0(cPtr, true);
  }

  public static IdentityPublicKeyV0 randomKeyArgs(KeyID id, Identifier contract_id, TimestampMillis timestamp_millis) {
    long cPtr = exampleJNI.randomKeyArgs(KeyID.getCPtr(id), id, Identifier.getCPtr(contract_id), contract_id, TimestampMillis.getCPtr(timestamp_millis), timestamp_millis);
    return (cPtr == 0) ? null : new IdentityPublicKeyV0(cPtr, true);
  }

  public static TimestampMillis timestampMillisCtor(java.math.BigInteger o_0) {
    long cPtr = exampleJNI.timestampMillisCtor(o_0);
    return (cPtr == 0) ? null : new TimestampMillis(cPtr, false);
  }

  public static void timestampMillisDestroy(TimestampMillis ffi) {
    exampleJNI.timestampMillisDestroy(TimestampMillis.getCPtr(ffi), ffi);
  }

  public static Identity getIdentityContractBounds(Identifier identifier, Identifier contract_identifier) {
    long cPtr = exampleJNI.getIdentityContractBounds(Identifier.getCPtr(identifier), identifier, Identifier.getCPtr(contract_identifier), contract_identifier);
    return (cPtr == 0) ? null : new Identity(cPtr, true);
  }

  public static Identity getIdentity2(Identifier identifier) {
    long cPtr = exampleJNI.getIdentity2(Identifier.getCPtr(identifier), identifier);
    return (cPtr == 0) ? null : new Identity(cPtr, true);
  }

  public static Result_ok_crate_identity_identity_Identity_err_crate_nested_ProtocolError createBasicIdentity(byte[] id, PlatformVersion _platform_version) {
    long cPtr = exampleJNI.createBasicIdentity(id, PlatformVersion.getCPtr(_platform_version), _platform_version);
    return (cPtr == 0) ? null : new Result_ok_crate_identity_identity_Identity_err_crate_nested_ProtocolError(cPtr, false);
  }

  public static Identity createBasicIdentityV0(byte[] id) {
    long cPtr = exampleJNI.createBasicIdentityV0(id);
    return (cPtr == 0) ? null : new Identity(cPtr, true);
  }

  public static KeyID keyIDCtor(long o_0) {
    long cPtr = exampleJNI.keyIDCtor(o_0);
    return (cPtr == 0) ? null : new KeyID(cPtr, false);
  }

  public static void keyIDDestroy(KeyID ffi) {
    exampleJNI.keyIDDestroy(KeyID.getCPtr(ffi), ffi);
  }

  public static void contractBoundsDestroy(ContractBounds ffi) {
    exampleJNI.contractBoundsDestroy(ContractBounds.getCPtr(ffi), ffi);
  }

  public static IdentityPublicKey identityPublicKeyV0Ctor(IdentityPublicKeyV0 o_0) {
    long cPtr = exampleJNI.identityPublicKeyV0Ctor(IdentityPublicKeyV0.getCPtr(o_0), o_0);
    return (cPtr == 0) ? null : new IdentityPublicKey(cPtr, false);
  }

  public static void identityPublicKeyDestroy(IdentityPublicKey ffi) {
    exampleJNI.identityPublicKeyDestroy(IdentityPublicKey.getCPtr(ffi), ffi);
  }

  public static byte[] vecU8Ctor(SWIGTYPE_p_unsigned_char values, long count) {
    return exampleJNI.vecU8Ctor(SWIGTYPE_p_unsigned_char.getCPtr(values), count);
  }

  public static void vecU8Destroy(byte[] ffi) {
    exampleJNI.vecU8Destroy(ffi);
  }

  public static Result_ok_crate_identity_identity_Identity_err_crate_nested_ProtocolError resultOkCrateIdentityIdentityIdentityErrCrateNestedProtocolErrorCtor(Identity ok, ProtocolError error) {
    long cPtr = exampleJNI.resultOkCrateIdentityIdentityIdentityErrCrateNestedProtocolErrorCtor(Identity.getCPtr(ok), ok, ProtocolError.getCPtr(error), error);
    return (cPtr == 0) ? null : new Result_ok_crate_identity_identity_Identity_err_crate_nested_ProtocolError(cPtr, false);
  }

  public static void resultOkCrateIdentityIdentityIdentityErrCrateNestedProtocolErrorDestroy(Result_ok_crate_identity_identity_Identity_err_crate_nested_ProtocolError ffi) {
    exampleJNI.resultOkCrateIdentityIdentityIdentityErrCrateNestedProtocolErrorDestroy(Result_ok_crate_identity_identity_Identity_err_crate_nested_ProtocolError.getCPtr(ffi), ffi);
  }

  public static std_collections_Map_keys_crate_identity_identity_KeyID_values_crate_identity_identity_IdentityPublicKey stdCollectionsMapKeysCrateIdentityIdentityKeyIDValuesCrateIdentityIdentityIdentityPublicKeyCtor(SWIGTYPE_p_p_KeyID keys, SWIGTYPE_p_p_IdentityPublicKey values, long count) {
    long cPtr = exampleJNI.stdCollectionsMapKeysCrateIdentityIdentityKeyIDValuesCrateIdentityIdentityIdentityPublicKeyCtor(SWIGTYPE_p_p_KeyID.getCPtr(keys), SWIGTYPE_p_p_IdentityPublicKey.getCPtr(values), count);
    return (cPtr == 0) ? null : new std_collections_Map_keys_crate_identity_identity_KeyID_values_crate_identity_identity_IdentityPublicKey(cPtr, false);
  }

  public static void stdCollectionsMapKeysCrateIdentityIdentityKeyIDValuesCrateIdentityIdentityIdentityPublicKeyDestroy(std_collections_Map_keys_crate_identity_identity_KeyID_values_crate_identity_identity_IdentityPublicKey ffi) {
    exampleJNI.stdCollectionsMapKeysCrateIdentityIdentityKeyIDValuesCrateIdentityIdentityIdentityPublicKeyDestroy(std_collections_Map_keys_crate_identity_identity_KeyID_values_crate_identity_identity_IdentityPublicKey.getCPtr(ffi), ffi);
  }

  public static SWIGTYPE_p_Vec_crate_nested_FeatureVersion vecCrateNestedFeatureVersionCtor(SWIGTYPE_p_p_FeatureVersion values, long count) {
    long cPtr = exampleJNI.vecCrateNestedFeatureVersionCtor(SWIGTYPE_p_p_FeatureVersion.getCPtr(values), count);
    return (cPtr == 0) ? null : new SWIGTYPE_p_Vec_crate_nested_FeatureVersion(cPtr, false);
  }

  public static void vecCrateNestedFeatureVersionDestroy(SWIGTYPE_p_Vec_crate_nested_FeatureVersion ffi) {
    exampleJNI.vecCrateNestedFeatureVersionDestroy(SWIGTYPE_p_Vec_crate_nested_FeatureVersion.getCPtr(ffi));
  }

  public static void setMemoryFactory(MemoryFactory value) {
    exampleJNI.memoryFactory_set(MemoryFactory.getCPtr(value), value);
  }

  public static MemoryFactory getMemoryFactory() {
    return new MemoryFactory(exampleJNI.memoryFactory_get(), false);
  }

  public static Identifier identifierClone(Identifier id) {
    long cPtr = exampleJNI.identifierClone(Identifier.getCPtr(id), id);
    return (cPtr == 0) ? null : new Identifier(cPtr, false);
  }

  public static ContractBounds singleContract(Identifier id) {
    long cPtr = exampleJNI.singleContract(Identifier.getCPtr(id), id);
    return (cPtr == 0) ? null : new ContractBounds(cPtr, true);
  }

  public static ContractBounds singleContractDocumentType(Identifier id, String type) {
    long cPtr = exampleJNI.singleContractDocumentType(Identifier.getCPtr(id), id, type);
    return (cPtr == 0) ? null : new ContractBounds(cPtr, true);
  }

}
