/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dash.sdk;

public class FeatureVersionBounds {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FeatureVersionBounds(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FeatureVersionBounds obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        exampleJNI.delete_FeatureVersionBounds(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMin_version(FeatureVersion value) {
    exampleJNI.FeatureVersionBounds_min_version_set(swigCPtr, this, FeatureVersion.getCPtr(value), value);
  }

  public FeatureVersion getMin_version() {
    long cPtr = exampleJNI.FeatureVersionBounds_min_version_get(swigCPtr, this);
    return (cPtr == 0) ? null : new FeatureVersion(cPtr, false);
  }

  public void setMax_version(FeatureVersion value) {
    exampleJNI.FeatureVersionBounds_max_version_set(swigCPtr, this, FeatureVersion.getCPtr(value), value);
  }

  public FeatureVersion getMax_version() {
    long cPtr = exampleJNI.FeatureVersionBounds_max_version_get(swigCPtr, this);
    return (cPtr == 0) ? null : new FeatureVersion(cPtr, false);
  }

  public void setDefault_current_version(FeatureVersion value) {
    exampleJNI.FeatureVersionBounds_default_current_version_set(swigCPtr, this, FeatureVersion.getCPtr(value), value);
  }

  public FeatureVersion getDefault_current_version() {
    long cPtr = exampleJNI.FeatureVersionBounds_default_current_version_get(swigCPtr, this);
    return (cPtr == 0) ? null : new FeatureVersion(cPtr, false);
  }

}
