/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dash.sdk;

public final class ferment_example_nested_model_snapshot_LLMQSnapshotSkipMode {
  public final static ferment_example_nested_model_snapshot_LLMQSnapshotSkipMode ferment_example_nested_model_snapshot_LLMQSnapshotSkipMode_NoSkipping = new ferment_example_nested_model_snapshot_LLMQSnapshotSkipMode("ferment_example_nested_model_snapshot_LLMQSnapshotSkipMode_NoSkipping", exampleJNI.ferment_example_nested_model_snapshot_LLMQSnapshotSkipMode_NoSkipping_get());
  public final static ferment_example_nested_model_snapshot_LLMQSnapshotSkipMode ferment_example_nested_model_snapshot_LLMQSnapshotSkipMode_SkipFirst = new ferment_example_nested_model_snapshot_LLMQSnapshotSkipMode("ferment_example_nested_model_snapshot_LLMQSnapshotSkipMode_SkipFirst", exampleJNI.ferment_example_nested_model_snapshot_LLMQSnapshotSkipMode_SkipFirst_get());
  public final static ferment_example_nested_model_snapshot_LLMQSnapshotSkipMode ferment_example_nested_model_snapshot_LLMQSnapshotSkipMode_SkipExcept = new ferment_example_nested_model_snapshot_LLMQSnapshotSkipMode("ferment_example_nested_model_snapshot_LLMQSnapshotSkipMode_SkipExcept", exampleJNI.ferment_example_nested_model_snapshot_LLMQSnapshotSkipMode_SkipExcept_get());
  public final static ferment_example_nested_model_snapshot_LLMQSnapshotSkipMode ferment_example_nested_model_snapshot_LLMQSnapshotSkipMode_SkipAll = new ferment_example_nested_model_snapshot_LLMQSnapshotSkipMode("ferment_example_nested_model_snapshot_LLMQSnapshotSkipMode_SkipAll", exampleJNI.ferment_example_nested_model_snapshot_LLMQSnapshotSkipMode_SkipAll_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ferment_example_nested_model_snapshot_LLMQSnapshotSkipMode swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ferment_example_nested_model_snapshot_LLMQSnapshotSkipMode.class + " with value " + swigValue);
  }

  private ferment_example_nested_model_snapshot_LLMQSnapshotSkipMode(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ferment_example_nested_model_snapshot_LLMQSnapshotSkipMode(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ferment_example_nested_model_snapshot_LLMQSnapshotSkipMode(String swigName, ferment_example_nested_model_snapshot_LLMQSnapshotSkipMode swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ferment_example_nested_model_snapshot_LLMQSnapshotSkipMode[] swigValues = { ferment_example_nested_model_snapshot_LLMQSnapshotSkipMode_NoSkipping, ferment_example_nested_model_snapshot_LLMQSnapshotSkipMode_SkipFirst, ferment_example_nested_model_snapshot_LLMQSnapshotSkipMode_SkipExcept, ferment_example_nested_model_snapshot_LLMQSnapshotSkipMode_SkipAll };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

