/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dash.sdk;

import org.dash.sdk.base.BaseObject;

public class InnerStruct extends BaseObject {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected InnerStruct(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(InnerStruct obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        exampleJNI.delete_InnerStruct(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected long getCPointer() {
    return swigCPtr;
  }

  public void setFirst(java.math.BigInteger value) {
    exampleJNI.InnerStruct_first_set(swigCPtr, this, value);
  }

  public java.math.BigInteger getFirst() {
    return exampleJNI.InnerStruct_first_get(swigCPtr, this);
  }

  public void setSecond(java.math.BigInteger value) {
    exampleJNI.InnerStruct_second_set(swigCPtr, this, value);
  }

  public java.math.BigInteger getSecond() {
    return exampleJNI.InnerStruct_second_get(swigCPtr, this);
  }

  public InnerStruct(int a, int b) {
    this(exampleJNI.new_InnerStruct(a, b), true);
  }

}
