/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dash.sdk;

public class OptionalFeatureVersion {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected OptionalFeatureVersion(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OptionalFeatureVersion obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        exampleJNI.delete_OptionalFeatureVersion(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void set_0(int value) {
    exampleJNI.OptionalFeatureVersion__0_set(swigCPtr, this, value);
  }

  public int get_0() {
    return exampleJNI.OptionalFeatureVersion__0_get(swigCPtr, this);
  }

}
