/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dash.sdk;

public class ProtocolError_UnknownVersionMismatch_Body {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ProtocolError_UnknownVersionMismatch_Body(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ProtocolError_UnknownVersionMismatch_Body obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        exampleJNI.delete_ProtocolError_UnknownVersionMismatch_Body(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMethod(String value) {
    exampleJNI.ProtocolError_UnknownVersionMismatch_Body_method_set(swigCPtr, this, value);
  }

  public String getMethod() {
    return exampleJNI.ProtocolError_UnknownVersionMismatch_Body_method_get(swigCPtr, this);
  }

  public void setKnown_versions(Vec_crate_nested_FeatureVersion value) {
    exampleJNI.ProtocolError_UnknownVersionMismatch_Body_known_versions_set(swigCPtr, this, Vec_crate_nested_FeatureVersion.getCPtr(value), value);
  }

  public Vec_crate_nested_FeatureVersion getKnown_versions() {
    long cPtr = exampleJNI.ProtocolError_UnknownVersionMismatch_Body_known_versions_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Vec_crate_nested_FeatureVersion(cPtr, false);
  }

  public void setReceived(FeatureVersion value) {
    exampleJNI.ProtocolError_UnknownVersionMismatch_Body_received_set(swigCPtr, this, FeatureVersion.getCPtr(value), value);
  }

  public FeatureVersion getReceived() {
    long cPtr = exampleJNI.ProtocolError_UnknownVersionMismatch_Body_received_get(swigCPtr, this);
    return (cPtr == 0) ? null : new FeatureVersion(cPtr, false);
  }

}
