/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dash.sdk;

public final class ProtocolError_Tag {
  public final static ProtocolError_Tag ProtocolError_IdentifierError = new ProtocolError_Tag("ProtocolError_IdentifierError");
  public final static ProtocolError_Tag ProtocolError_StringDecodeError = new ProtocolError_Tag("ProtocolError_StringDecodeError");
  public final static ProtocolError_Tag ProtocolError_StringDecodeError2 = new ProtocolError_Tag("ProtocolError_StringDecodeError2");
  public final static ProtocolError_Tag ProtocolError_EmptyPublicKeyDataError = new ProtocolError_Tag("ProtocolError_EmptyPublicKeyDataError");
  public final static ProtocolError_Tag ProtocolError_MaxEncodedBytesReachedError = new ProtocolError_Tag("ProtocolError_MaxEncodedBytesReachedError");
  public final static ProtocolError_Tag ProtocolError_EncodingError = new ProtocolError_Tag("ProtocolError_EncodingError");
  public final static ProtocolError_Tag ProtocolError_EncodingError2 = new ProtocolError_Tag("ProtocolError_EncodingError2");
  public final static ProtocolError_Tag ProtocolError_DataContractNotPresentError = new ProtocolError_Tag("ProtocolError_DataContractNotPresentError");
  public final static ProtocolError_Tag ProtocolError_UnknownVersionMismatch = new ProtocolError_Tag("ProtocolError_UnknownVersionMismatch");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ProtocolError_Tag swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ProtocolError_Tag.class + " with value " + swigValue);
  }

  private ProtocolError_Tag(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ProtocolError_Tag(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ProtocolError_Tag(String swigName, ProtocolError_Tag swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ProtocolError_Tag[] swigValues = { ProtocolError_IdentifierError, ProtocolError_StringDecodeError, ProtocolError_StringDecodeError2, ProtocolError_EmptyPublicKeyDataError, ProtocolError_MaxEncodedBytesReachedError, ProtocolError_EncodingError, ProtocolError_EncodingError2, ProtocolError_DataContractNotPresentError, ProtocolError_UnknownVersionMismatch };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

