/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dash.sdk;

public final class Purpose {
  public final static Purpose Purpose_AUTHENTICATION = new Purpose("Purpose_AUTHENTICATION", exampleJNI.Purpose_AUTHENTICATION_get());
  public final static Purpose Purpose_ENCRYPTION = new Purpose("Purpose_ENCRYPTION", exampleJNI.Purpose_ENCRYPTION_get());
  public final static Purpose Purpose_DECRYPTION = new Purpose("Purpose_DECRYPTION", exampleJNI.Purpose_DECRYPTION_get());
  public final static Purpose Purpose_WITHDRAW = new Purpose("Purpose_WITHDRAW", exampleJNI.Purpose_WITHDRAW_get());
  public final static Purpose Purpose_SYSTEM = new Purpose("Purpose_SYSTEM", exampleJNI.Purpose_SYSTEM_get());
  public final static Purpose Purpose_VOTING = new Purpose("Purpose_VOTING", exampleJNI.Purpose_VOTING_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static Purpose swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + Purpose.class + " with value " + swigValue);
  }

  private Purpose(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private Purpose(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private Purpose(String swigName, Purpose swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static Purpose[] swigValues = { Purpose_AUTHENTICATION, Purpose_ENCRYPTION, Purpose_DECRYPTION, Purpose_WITHDRAW, Purpose_SYSTEM, Purpose_VOTING };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

