/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dash.sdk;

public class VecU8Holder {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected VecU8Holder(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VecU8Holder obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        exampleJNI.delete_VecU8Holder(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setFirst(byte[] value) {
    exampleJNI.VecU8Holder_first_set(swigCPtr, this, value);
  }

  public byte[] getFirst() {
    return exampleJNI.VecU8Holder_first_get(swigCPtr, this);
  }

  public VecU8Holder(byte[] vec_u8) {
    this(exampleJNI.new_VecU8Holder(vec_u8), true);
  }

}
